adding v3.0.0

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -17,10 +17,10 @@ DISTFILES = $(INSTFILES) \
 	ChangeLog INSTALL ONEWS OONEWS README VERSION VERSION-NICK \
 	Makeconf.in Makefile.in Makefile.fw \
 	config.site configure configure.ac
-SUBDIRS = m4 tools doc etc share src tests @USE_NLS_TRUE@ po
-SUBDIRS_WITH_NO_BUILD = @USE_NLS_FALSE@ po
+SUBDIRS = m4 tools doc etc share src tests
+SUBDIRS_WITH_NO_BUILD = po
 
-all: Makefile Makeconf R docs recommended vignettes
+all: Makefile Makeconf R docs recommended vignettes javaconf
 recommended: @USE_RECOMMENDED_PACKAGES_TRUE@ stamp-recommended
 
 Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
@@ -37,7 +37,6 @@ ACINCLUDE_DEPENDENCIES = \
 	m4/clibs.m4 \
 	m4/codeset.m4 \
 	m4/gettext.m4 m4/gettext-lib.m4 \
-	m4/java.m4 \
 	m4/libtool.m4 m4/ltoptions.m4 m4/ltversion.m4 m4/ltsugar.m4 m4/lt~obsolete.m4 \
 	m4/stat-time.m4
 CONFIGURE_DEPENDENCIES = $(srcdir)/VERSION
@@ -78,6 +77,16 @@ stamp-recommended: R docs
 vignettes: stamp-recommended
 	@(cd src/library && $(MAKE) $@)
 
+## This needs packages built, hence 'R' dependence on 'javaconf'
+stamp-java : etc/javaconf bin/javareconf
+	@$(ECHO) "configuring Java ..."
+	@-bin/R CMD javareconf
+	@touch stamp-java
+
+javaconf: R
+	@$(MAKE) stamp-java
+
+
 install install-strip: installdirs svnonly
 	@for d in $(SUBDIRS); do \
 	  (cd $${d} && $(MAKE) $@) || exit 1; \
@@ -94,9 +103,13 @@ svnonly:
 	@if test ! -f "$(srcdir)/doc/FAQ" || test -f non-tarball ; then \
 	  (cd doc/manual && $(MAKE) front-matter html-non-svn) ; \
 	  touch non-tarball ; \
-	  (cd $(srcdir); LC_ALL=C TZ=GMT svn info || $(ECHO) "Revision: unknown") 2> /dev/null \
+	  (cd $(srcdir); LC_ALL=C TZ=GMT svn info || $(ECHO) "Revision: -99") 2> /dev/null \
 	    | sed -n -e '/^Revision/p' -e '/^Last Changed Date/'p \
 	    | cut -d' ' -f1,2,3,4 > SVN-REVISION-tmp ; \
+	  if test "`cat SVN-REVISION-tmp`" = "Revision: -99"; then \
+	    $(ECHO) "ERROR: not an svn checkout"; \
+	    exit 1; \
+	  fi; \
 	  $(SHELL) $(top_srcdir)/tools/move-if-change SVN-REVISION-tmp SVN-REVISION ; \
 	  rm -f SVN-REVISION-tmp ; \
 	else \
@@ -137,6 +150,7 @@ clean:
 distclean: clean
 	@(for d in $(SUBDIRS); do rsd="$${d} $${rsd}"; done; \
 	  for d in $${rsd}; do (cd $${d} && $(MAKE) $@); done)
+	@rm -f po/Makefile
 	-@rm -rf bin include lib library modules gnome
 	@if test -f non-tarball ; then \
 	  rm -f $(NON_SVN_INSTFILES) NEWS NEWS.pdf non-tarball doc/FAQ doc/RESOURCES doc/html/resources.html doc/html/NEWS.html; \
@@ -146,7 +160,7 @@ distclean: clean
 	fi
 	-@rm -rf libconftest.dSYM
 	-@rm -f Makeconf Makefile Makefile.bak Makefrag.* \
-	  config.cache config.log config.status libtool \
+	  config.cache config.log config.status libtool stamp-java \
 	  $(ACLOCAL_M4) acinclude.m4 $(distdir).tar.gz
 maintainer-clean: distclean
 	@$(ECHO) "This command is intended for maintainers to use; it"
diff --git a/src/scripts/javareconf b/src/scripts/javareconf
--- a/src/scripts/javareconf
+++ b/src/scripts/javareconf
@@ -3,10 +3,13 @@ if test -z "${R_HOME}"; then
     exit 1
 fi
 
+## pick up configure-time settings
+. "${R_HOME}/etc${R_ARCH}/javaconf"
+
 DYLIB_EXT=`${R_HOME}/bin/R CMD config DYLIB_EXT`
 tools_classpath=${R_SHARE_DIR}/java
 
-revision='$Rev: 62021 $'
+revision='$Rev: 62022 $'
 version=`set - ${revision}; echo ${2}`
 version="R Java configurator: ${R_VERSION} (r${version})
 
@@ -130,22 +133,20 @@ if test -z "$JAVAC"; then
     IFS=${save_IFS}
 fi
 
+: ${TMPDIR=/tmp}
+{ tempdir=`(mktemp -d -q "${TMPDIR}/RJRECONF.XXXXXX") 2>/dev/null` \
+	&& test -n "${tempdir}" && test -d "${tempdir}" ; } ||
+{ test -n "${RANDOM}" && tempdir=${TMPDIR}/RJRECONF$$-${RANDOM} \
+	&& (mkdir "${tempdir}") ; } ||
+{ tempdir=${TMPDIR}/RJRECONF.$$-`date +%m%d%H%M%S` \
+	&& (mkdir "${tempdir}"); } ||
+{ tempdir=${TMPDIR}/RJRECONF.$$ && (mkdir "${tempdir}") ; } ||
+    (error "cannot create temporary directory" && exit 1)
+
 # test functionality of the compiler
 javac_works='not present'
 if test -n "$JAVAC"; then
     javac_works='not functional'
-#    tempdir=`mktemp -d`
-
-    : ${TMPDIR=/tmp}
-    { tempdir=`(mktemp -d -q "${TMPDIR}/RJRECONF.XXXXXX") 2>/dev/null` \
-	&& test -n "${tempdir}" && test -d "${tempdir}" ; } ||
-    { test -n "${RANDOM}" && tempdir=${TMPDIR}/RJRECONF$$-${RANDOM} \
-	&& (mkdir "${tempdir}") ; } ||
-    { tempdir=${TMPDIR}/RJRECONF.$$-`date +%m%d%H%M%S` \
-	&& (mkdir "${tempdir}"); } ||
-    { tempdir=${TMPDIR}/RJRECONF.$$ && (mkdir "${tempdir}") ; } ||
-    (error "cannot create temporary directory" && exit 1)
-
     echo "public class A { }" > ${tempdir}/A.java
     if test -f ${tempdir}/A.java; then
 	if "${JAVAC}" ${tempdir}/A.java >/dev/null; then
@@ -154,8 +155,6 @@ if test -n "$JAVAC"; then
 	    fi
 	fi
     fi
-    rm -rf ${tempdir}
-
 fi
 if test "${javac_works}" = yes; then
     echo "Java compiler    : ${JAVAC}"
@@ -197,15 +196,22 @@ custom_JAVA_LD_LIBRARY_PATH="${JAVA_LD_LIBRARY_PATH}"
 
 # sys-dependent tweaks to JNI flags
 hostos=`uname 2>/dev/null`
-## NB: that is not the same name as in configuration.
-case "$hostos" in
-    Darwin*)
-	JAVA_LD_LIBRARY_PATH=
-	JAVA_LIBS="-framework JavaVM"
-        JAVA_CPPFLAGS="-I/System/Library/Frameworks/JavaVM.framework/Headers"
+if test "${hostos}" = "Darwin"; then
+     pref=`echo "${JAVA_HOME}" | grep "/Home$"`
+     if test "${pref}" = "${JAVA_HOME}"; then 
+       echo "System Java on OS X"
+       JAVA_CPPFLAGS="-I/System/Library/Frameworks/JavaVM.framework/Headers"
+       JAVA_LIBS="-framework JavaVM"
+       JAVA_LD_LIBRARY_PATH=
 	has_libjvm=unknown
-	;;
-    *)
+    else
+       echo "Non-system Java on OS X"
+    fi
+fi
+## we now look for a path to put in R_LD_LIBRARY_PATH which will
+## enable libjvm to be found at run time.  This should not be needed,
+## but it seems that libjvm is often not in the ld.so cache.
+if test "${JAVA_LIBS}" = "~autodetect~"; then
 	## we need to reset LD_LIBRARY_PATH, because Java automatically
 	## adds all LD_LIBRARY_PATH to Java path
 	save_LDLP=${LD_LIBRARY_PATH}
@@ -219,13 +225,12 @@ case "$hostos" in
 	for dir in ${java_library_path}; do
 	    if test -f "$dir/libjvm${DYLIB_EXT}"; then
 		has_libjvm=yes
+		java_library_path="${dir}"
 		break
 	    fi
 	done
 	# Then try some heuristics using sun.boot.library.path
 	if test ${has_libjvm} = no; then
-	    echo "NOTE: Your JVM has a bogus java.library.path system property!" >&2
-	    echo "      Trying a heuristic via sun.boot.library.path to find jvm library..." >&2
 	    boot_path=`"$JAVA" -classpath "${tools_classpath}" getsp sun.boot.library.path| ${SED-sed} -e 's/:$//' -e 's/^://'`
 	    if test -n "${boot_path}"; then
 		for dir in "${boot_path}" "${boot_path}/client" "${boot_path}/server"; do
@@ -291,8 +296,7 @@ case "$hostos" in
            fi
 	   JAVA_CPPFLAGS=`echo ${JAVA_CPPFLAGS} | ${SED-sed} -e s:${JAVA_HOME}:\$\(JAVA_HOME\):g`
         fi
-	;;
-esac
+fi
 
 if test -n "${add_java_libs}"; then JAVA_LIBS="${JAVA_LIBS} ${add_java_libs}"; fi
 
@@ -309,30 +313,49 @@ fi
 if test "${custom_JAVA_LD_LIBRARY_PATH}" != '~autodetect~'; then
   JAVA_LD_LIBRARY_PATH="${custom_JAVA_LD_LIBRARY_PATH}"
   JAVA_LD_LIBRARY_PATH_SH=`echo ${JAVA_LD_LIBRARY_PATH}|${SED-sed} -e 's:$(JAVA_HOME):\$\{JAVA_HOME\}:g'`
-  if test "${acx_custom_java_libs}" != yes; then
-    echo ''
-    echo ' ** Warning: you are using custom JAVA_LD_LIBRARY_PATH without' >&2
-    echo '    custom JAVA_LIBS. We cannot guarantee that this will work,' >&2
-    echo '    both settings must match for a proper Java operation!' >&2
-  fi
-else
-    if test "${has_libjvm}" = no; then
-	echo ''
-	echo ' ** WARNING: auto-detection could not find libjvm!' >&2
-	echo '    Your JVM has likely invalid java.library.path property,' >&2	
-	echo '    you may want to fix the JVM or set JAVA_LD_LIBRARY_PATH manually.' >&2	
-    fi
-  if test "${acx_custom_java_libs}" = yes; then
-    echo ''
-    echo ' ** Warning: you are using custom JAVA_LIBS setting without' >&2
-    echo '    specifying JAVA_LD_LIBRARY_PATH. We cannot guarantee that' >&2
-    echo '    this will work, both must match for a proper Java operation!' >&2
-  fi
 fi
 
-echo "Java library path: ${JAVA_LD_LIBRARY_PATH}"
-echo "JNI linker flags : ${JAVA_LIBS}"
-echo "JNI cpp flags    : ${JAVA_CPPFLAGS}"
+## Do cpmpile test in the temporary dir
+wd=${PWD}
+cd ${tempdir}
+
+echo
+echo "trying to compile and link a JNI progam "
+echo "detected JNI cpp flags    : ${JAVA_CPPFLAGS}"
+echo "detected JNI linker flags : ${JAVA_LIBS}"
+
+cat <<_ACEOF >conftest.c
+#include <jni.h>
+
+int main(void) {
+    JNI_CreateJavaVM(0, 0, 0);
+    return 0;
+}
+_ACEOF
+
+JAVA_CPPFLAGS1=`echo ${JAVA_CPPFLAGS}|${SED-sed} -e 's:$(JAVA_HOME):'"${JAVA_HOME}:g"`
+JAVA_LIBS1=`echo ${JAVA_LIBS}|${SED-sed} -e 's:$(JAVA_HOME):'"${JAVA_HOME}:g"`
+cat <<_ACEOF >Makevars
+PKG_CPPFLAGS = ${JAVA_CPPFLAGS1}
+PKG_LIBS = ${JAVA_LIBS1}
+_ACEOF
+
+## in case e.g. -k was passed in the environment
+export MAKEFLAGS=
+${R_HOME}/bin/R CMD SHLIB conftest.c
+ac_status=$?
+
+if test $ac_status != 0; then
+  echo "Unable to compile a JNI program"
+  JAVA_LD_LIBRARY_PATH=
+  JAVA_LIBS=
+  JAVA_CPPFLAGS=
+fi
+
+rm -f conftest.c conftest.o conftest.so Makevars
+cd ${wd}
+rm -rf ${tempdir}
+
 
 echo ""
 
@@ -352,6 +375,11 @@ if test "${export_vars}" = yes; then
     ${run_prog}
     exit 0
 fi
+
+echo ""
+echo "Java library path: ${JAVA_LD_LIBRARY_PATH}"
+echo "JNI cpp flags    : ${JAVA_CPPFLAGS}"
+echo "JNI linker flags : ${JAVA_LIBS}"
 
 test "${dry_run}" = yes && exit 0
 
