adding v1.4.0

diff --git a/src/scripts/INSTALL.in b/src/scripts/INSTALL.in
--- a/src/scripts/INSTALL.in
+++ b/src/scripts/INSTALL.in
@@ -4,7 +4,7 @@
 
 # @configure_input@
 
-revision='$Revision: 1.68.4.1 $'
+revision='$Revision: 1.82 $'
 version=`set - ${revision}; echo ${2}`
 version="R add-on package installer ${version}
 
@@ -30,9 +30,10 @@ Options:
       --configure-vars=VARS
                         set variables for the configure script (if any)
   -c, --clean		remove all files created during installation
-  -s, --save            save the package source as an image file, and
+  -s, --save[=ARGS]     save the package source as an image file, and
                         arrange for this file to be loaded when the
-                        package is attached
+                        package is attached; if given, ARGS are passed
+                        to R when creating the save image
       --no-save         do not save the package source as an image file
   -d, --debug		turn on shell and build-help debugging
   -l, --library=LIB	install packages to library tree LIB
@@ -46,7 +47,7 @@ Report bugs to <r-bugs@r-project.org>."
 
 R_VERSION='@VERSION@'
 INSTALL='@INSTALL@'
-MAKE=${MAKE-@MAKE@}
+MAKE=${MAKE-'@MAKE@'}
 NO_PERL5=@NO_PERL5@
 NO_PERL5_MSG="\
 *** Formatting and installing R help pages needs Perl version 5, which
@@ -96,6 +97,7 @@ configure_args=
 configure_vars=
 
 save="CHECK"
+save_args="--no-site-file --no-init-file";
 
 while test -n "${1}"; do
   case ${1} in
@@ -106,7 +108,9 @@ while test -n "${1}"; do
     -c|--clean)
       clean=true ;;
     -s|--save)
-      save=true ;;
+      save=true;;
+    --save=*)
+      save_args=`echo "${1}" | sed -e 's/[^=]*=//'` ;;
     --no-save)
       save=false ;;
     -d|--debug)
@@ -225,10 +229,23 @@ do_install () {
 
   mkdir -p ${lib}/${pkg} || exit 3
 
-  if test -d man; then
-    ## Assume this is a source package.
-    ## FIXME:  Do we have a better test?
-    echo "Installing source package \`${pkg}' ..."
+  ## Figure out whether this is a source or binary package.
+  if grep "^Built:" DESCRIPTION >/dev/null ; then
+    ## If DESCRIPTION has a 'Built:' entry this is a binary package.
+    ## This is the right test but available only for recently enough
+    ## installed packages.
+    is_source_package=false
+  elif test -d man; then
+    ## Versions of R prior to 1.4 did not install man pages.  Hence
+    ## assuming that source packages would have some documentation ...
+    is_source_package=true
+  else
+    is_source_package=false
+  fi
+
+  if ${is_source_package}; then
+    ## This is a source package ... hopefully.
+    echo "Installing *source* package \`${pkg}' ..."
 
     ## Make the destination directories available to the developer's
     ## installation scripts (e.g. configure, etc.)
@@ -258,7 +275,7 @@ do_install () {
 	    makefiles="-f Makevars ${makefiles}"
 	  fi
 	  ${MAKE} ${makefiles} \
-	    && cp *.@SHLIB_EXT@ ${lib}/${pkg}/libs \
+	    && cp *@SHLIB_EXT@ ${lib}/${pkg}/libs \
 	    || error=true; \
 	  if ${clean}; then
 	    ${MAKE} clean
@@ -268,12 +285,12 @@ do_install () {
         cd src;
           srcs=`ls *.[cfC] *.cc *.cpp 2>/dev/null`
 	  if test -n "${srcs}"; then
-	    sh ${R_HOME}/bin/SHLIB -o ${pkg}.@SHLIB_EXT@ ${srcs} \
-	      && cp *.@SHLIB_EXT@ ${lib}/${pkg}/libs \
+	    sh ${R_HOME}/bin/SHLIB -o ${pkg}@SHLIB_EXT@ ${srcs} \
+	      && cp *@SHLIB_EXT@ ${lib}/${pkg}/libs \
   	      || error=true; \
 	    if ${clean}; then
 	      rm -rf .libs _libs
-	      rm -f *.o *.@SHLIB_EXT@
+	      rm -f *.o *@SHLIB_EXT@
 	    fi
 	  else
 	    echo "WARNING: no source files found"
@@ -292,13 +309,15 @@ do_install () {
       Rsrcs=`ls R/*.[RSqrs] R/unix/*.[RSqrs] 2>/dev/null`
       if test -n "${Rsrcs}"; then
         mkdir -p ${lib}/${pkg}/R
-        cat  ${Rsrcs} > ${lib}/${pkg}/R/${pkg}
+	rm -f ${lib}/${pkg}/R/*
+        cat ${Rsrcs} > ${lib}/${pkg}/R/${pkg}
       fi
     fi
 
     if test -d data; then
       echo " data"
       mkdir -p ${lib}/${pkg}/data
+      rm -f ${lib}/${pkg}/data/*
       cp data/* ${lib}/${pkg}/data
       chmod 644 ${lib}/${pkg}/data/*
       if test -n "${use_zip_data}" \
@@ -313,6 +332,7 @@ do_install () {
     if test -d demo; then
       echo " demo"
       mkdir -p ${lib}/${pkg}/demo
+      rm -f ${lib}/${pkg}/demo/*
       cp demo/* ${lib}/${pkg}/demo
       chmod 644 ${lib}/${pkg}/demo/*
     fi
@@ -320,6 +340,7 @@ do_install () {
     if test -d exec; then
       echo " exec"
       mkdir -p ${lib}/${pkg}/exec
+      rm -f ${lib}/${pkg}/exec/*
       cp exec/* ${lib}/${pkg}/exec
       chmod 755 ${lib}/${pkg}/exec/*
     fi
@@ -331,7 +352,7 @@ do_install () {
 
     case ${save} in
       CHECK)
-	if test -r INSTALL.R; then
+	if test -r install.R; then
 	  R_SAVE_IMAGE=true;
         else
 	  R_SAVE_IMAGE=false;
@@ -344,36 +365,30 @@ do_install () {
 
     if ${R_SAVE_IMAGE}; then
       echo " save image"
-      if test -s "R_PROFILE.R"; then true
-      else
-        echo "options(echo=FALSE)" > R_PROFILE.R
+      ## <NOTE>
+      ## We want R to run as quietly as possible when creating the save
+      ## image.  But this is tricky: sending options(echo=FALSE) to R via
+      ## stdin (as opposed to writing to a file and reading from it)
+      ## echoes what we sent before shutting up R, which is not what we
+      ## want.  Option '--slave' gets around this but also turns off
+      ## saving ... hence we call R with '--slave --save'.  Argh.
+      (if test -s R_PROFILE.R; then cat R_PROFILE.R; fi; \
+        echo "invisible(.libPaths(c(\"${lib}\", .libPaths())))"; \
+        cat ${lib}/${pkg}/R/${pkg}) | \
+	${R_HOME}/bin/R --slave --save ${save_args}
+      ## </NOTE>
+      if test ${?} -ne 0; then
+        echo "ERROR: execution of package source for ${pkg} failed"
+	exit 1
       fi
-      R_PROFILE=./R_PROFILE.R
-      export R_PROFILE
-      (echo " .lib.loc <- c(\"${lib}\", .lib.loc)";
-        cat ${lib}/${pkg}/R/${pkg};
-        echo "rm(.lib.loc)") | ${R_HOME}/bin/R --save --silent \
-          || (echo "Execution of package source for ${pkg} failed"; exit 1)
       mv .RData ${lib}/${pkg}/R/all.rda
       mv ${lib}/${pkg}/R/${pkg} ${lib}/${pkg}/R/${pkg}.R
-      if test -s INSTALL.R; then cp INSTALL.R ${lib}/${pkg}/R/${pkg}
-      else
-        cat > ${lib}/${pkg}/R/${pkg} <<EOF
-.First.lib <- function(libname, pkgname) {
-  fullName <- paste("package", pkgname, sep=":")
-  myEnv <- pos.to.env(match(fullName, search()))
-  dataFile <- file.path(libname, pkgname, "R", "all.rda")
-  rm(.First.lib, envir = myEnv)
-  load(dataFile, myEnv)
-  if(exists(".First.lib", envir = myEnv, inherits = FALSE)) {
-    f <- get(".First.lib", envir = myEnv, inherits = FALSE)
-    if(is.function(f))
-      f(libname, pkgname)
-    else
-      stop(paste("package \"", pkgname, "\"has a non-function .First", sep=""))
-  }
-}
-EOF
+      cat ${R_HOME}/share/R/firstlib.R > ${lib}/${pkg}/R/${pkg}
+      ## if install.R is non-empty, arrange to evaluate the R code it
+      ## contains after the package source (maybe for some kind of
+      ## cleanup).
+      if test -s install.R; then
+        cat install.R >> ${lib}/${pkg}/R/${pkg}
       fi
     fi
 
@@ -398,6 +413,15 @@ EOF
 
     if test -d man; then
       echo " help"
+      ## Install man sources ...
+      Rdfiles=`ls man/*.[Rr]d man/unix/*.[Rr]d 2>/dev/null`
+      if test -n "${Rdfiles}"; then
+	mkdir -p ${lib}/${pkg}/man
+	rm -f ${lib}/${pkg}/man/*
+	cat ${Rdfiles} > ${lib}/${pkg}/man/${pkg}.Rd
+	chmod 644 ${lib}/${pkg}/man/${pkg}.Rd
+      fi
+      ## Maybe build preformatted help pages ...
       if ${build_help}; then
 	if ${NO_PERL5}; then
 	  echo "${NO_PERL5_MSG}"
@@ -412,7 +436,7 @@ EOF
 	    exit 6
 	  fi
 	  ${R_CMD} perl ${R_HOME}/share/perl/Rd2contents.pl \
-	    ../${pkg} > ${lib}/${pkg}/CONTENTS
+	    --os=unix ../${pkg} > ${lib}/${pkg}/CONTENTS
 	  if test ${lib} = ${R_HOME}/library; then 
 	    ${R_CMD} perl ${R_HOME}/share/perl/build-help.pl --htmllists
 	    cat ${R_HOME}/library/*/CONTENTS \
@@ -446,8 +470,8 @@ EOF
     fi
 
   else  
-    ## Assume this is a binary package
-    echo "Installing binary package \`${pkg}' ..."
+    ## This is a binary package ... hopefully.
+    echo "Installing *binary* package \`${pkg}' ..."
     cp -r . ${lib}/${pkg}
   fi
 
