adding v2.1.0

diff --git a/src/scripts/INSTALL.in b/src/scripts/INSTALL.in
--- a/src/scripts/INSTALL.in
+++ b/src/scripts/INSTALL.in
@@ -8,7 +8,7 @@ revision='$Revision: 1.161 $'
 version=`set - ${revision}; echo ${2}`
 version="R add-on package installer ${version}
 
-Copyright (C) 2000-2004 The R Core Development Team.
+Copyright (C) 2000-2005 The R Core Development Team.
 This is free software; see the GNU General Public Licence version 2
 or later for copying conditions.  There is NO warranty."
 
@@ -52,6 +52,7 @@ Options:
       --fake		do minimal install for testing purposes
       --no-lock		install on top of any existing installation
                         without using a lock directory
+      --build           build binary tarball(s) of the installed package(s)
 
 Report bugs to <r-bugs@r-project.org>."
 
@@ -90,14 +91,14 @@ warning () { echo "WARNING: $*" >&2 ; }
 error ()   { echo "ERROR: $*" >&2 ; }
 
 startdir=`${GETWD}`
-tmpdir="${TMPDIR-/tmp}/R.INSTALL.$$"
-if (test -d "${tmpdir}" && test -w "${tmpdir}") || \
-    ${MKDIR_P} "${tmpdir}" 2> /dev/null; then
-  tmpdir=`cd "${tmpdir}" && ${GETWD}`
-else
-  error "cannot write to or create temporary directory '${tmpdir}'"
-  exit 1
-fi
+: ${TMPDIR=/tmp}
+{ tmpdir=`(mktemp -d -q "${TMPDIR}/R.INSTALL.XXXXXX") 2>/dev/null` \
+    && test -n "${tmpdir}" && test -d "${tmpdir}" ; } ||
+  { test -n "${RANDOM}" && tmp=${TMPDIR}/R.INSTALL$$-${RANDOM} \
+      && (${MKDIR_P} "${tmpdir}") ; } ||
+  { tmpdir=${TMPDIR}/R.INSTALL.$$ && (${MKDIR_P} "${tmpdir}") ; } ||
+  (error "cannot create temporary directory" && exit 1)
+tmpdir=`cd "${tmpdir}" && ${GETWD}`
 
 : ${R_OSTYPE=unix}
 ## <NOTE>
@@ -117,6 +118,12 @@ stars="*"
 
 . "${R_HOME}/share/sh/dcf.sh"	# get_dcf_field()
 
+tilde_expand () {
+    h=`echo "${HOME}" | sed 's,/,\\\/,g'`
+    ## (Need to escape whatever we use as sed delimiter.)
+    echo "$1" | sed "s/^~/${h}/"
+}
+
 get_packages () {
   ## get the full path names to all packages contained in $1.
   ## NOTE: modifies pkgs!
@@ -127,10 +134,8 @@ get_packages () {
       if test -f "${1}/${p}/DESCRIPTION.in"; then
         ## Try being defensive about missing final newlines, or extra
 	## empty lines.
-        (cat "${1}/${p}/DESCRIPTION.in"
-	  echo
-          grep -v "^Contains:" "${1}/DESCRIPTION"
-	  echo) | sed '/^ *$/d' > "${1}/${p}/DESCRIPTION"
+        (cat "${1}/${p}/DESCRIPTION.in" "${1}/DESCRIPTION"
+	 echo) | sed '/^ *$/d' > "${1}/${p}/DESCRIPTION"
       fi
     done
   else
@@ -155,6 +160,14 @@ parse_description_field () { # fieldname
     esac
   else
     value="missing"
+  fi
+}
+
+do_cleanup_tmpdir () {
+  ## Solaris will not remove any directory in the current path
+  cd "${startdir}"
+  if test -d "${tmpdir}"; then
+    rm -rf "${tmpdir}"
   fi
 }
 
@@ -188,14 +201,15 @@ fake=false
 lazy="auto"
 lazy_data=false
 lock=true
+tar_up=false
 
 while test -n "${1}"; do
   ##DBG echo "   in 'R INSTALL' --arg checking-- \$1 = '${1}'" # Debugging
   case ${1} in
     -h|--help)
-      echo "${usage}"; exit 0 ;;
+      echo "${usage}"; do_cleanup_tmpdir; exit 0 ;;
     -v|--version)
-      echo "${version}"; exit 0 ;;
+      echo "${version}"; do_cleanup_tmpdir; exit 0 ;;
     -c|--clean)
       clean=true ;;
     -s|--save)
@@ -250,6 +264,8 @@ while test -n "${1}"; do
       fake=true ;;
     --no-lock)
       lock=false ;;
+    --build)
+      tar_up=true ;;
     *)
       if test -f "${1}"; then
 	##DBG echo "  in 'R INSTALL' --arg checking-- FILE '${1}'"
@@ -263,11 +279,23 @@ while test -n "${1}"; do
 	## Otherwise, the build date for an older version may be newer
 	## than the modification date for the new sources as recorded in
 	## the tarball ...
-	gzip -dc "${1}" | (cd "${tmpdir}" && ${TAR} -mxf -)
-	if test -f "${tmpdir}/${pkgname}/DESCRIPTION"; then
+	${R_GZIPCMD} -dc "${1}" | (cd "${tmpdir}" && ${TAR} -mxf -)
+	## If we have a binary bundle distribution, the DESCRIPTION file
+	## is at top level.
+	if test -f "${tmpdir}/DESCRIPTION"; then
+	  if grep "^Contains:" "${tmpdir}/DESCRIPTION" >/dev/null; then
+	     message "Looks like a binary bundle"
+	     get_packages "${tmpdir}"
+	  else
+	    error "unknown package layout"
+	    do_cleanup_tmpdir;
+	    exit 1
+	  fi
+	elif test -f "${tmpdir}/${pkgname}/DESCRIPTION"; then
 	  get_packages "${tmpdir}/${pkgname}"
 	else
 	  error "cannot extract package from '${1}'"
+	  do_cleanup_tmpdir;
 	  exit 1
 	fi
       elif test -f "${1}/DESCRIPTION"; then
@@ -281,6 +309,12 @@ while test -n "${1}"; do
   shift
 done
 
+if (${tar_up} && ${fake}); then
+  error "building a fake installation is disallowed"
+  do_cleanup_tmpdir;
+  exit 1
+fi
+
 if ${debug} ; then
   echo "'Rcmd INSTALL': in startdir= $startdir with tmpdir= $tmpdir"
   echo "   lib= '$lib', pkgs= '$pkgs'"
@@ -288,14 +322,17 @@ fi
 
 if test -z "${pkgs}"; then
   error "no packages specified"
+  do_cleanup_tmpdir;
   exit 1
 fi
 
+lib=`tilde_expand "${lib}"`
 if (test -d "${lib}" && test -w "${lib}") || \
     ${MKDIR_P} "${lib}" 2> /dev/null; then
   lib=`cd "${lib}" && ${GETWD}`
 else
   error "cannot write to or create directory '${lib}'"
+  do_cleanup_tmpdir;
   exit 2
 fi
 if ${lock} ; then
@@ -304,12 +341,14 @@ if ${lock} ; then
   if test -d "${lockdir}" || test -f "${lockdir}"; then
     error "failed to lock directory '${lib}' for modifying"
     echo "Try removing '${lockdir}'" >&2
+    do_cleanup_tmpdir;
     exit 3
   else
     ${MKDIR_P} "${lockdir}"
     if test ${?} -ne 0; then
       ## This should not really happen ...
       error "failed to lock directory '${lib}' for modifying"
+      do_cleanup_tmpdir;
       exit 3
     fi
   fi
@@ -373,6 +412,9 @@ do_install_binary () {
     error "installing binary package failed"
     do_exit_on_error
   fi
+  if ${tar_up} ; then
+    echo "${pkg} was already a binary package and will not be rebuilt"
+  fi
 }
 
 ### 
@@ -393,6 +435,39 @@ do_install_source () {
   export R_PACKAGE_DIR
   export R_PACKAGE_NAME
 
+  Type=`get_dcf_field Type DESCRIPTION`
+  if test "$Type" = "Frontend" ; then
+    message "Installing *Frontend* package '${pkg_name}' ..."
+    if ${use_configure} && test -x ./configure ; then
+      eval ${configure_vars} ./configure ${configure_args}
+      if test ${?} -ne 0; then
+	error "configuration failed for package '${pkg_name}'"
+	do_exit_on_error
+      fi
+    fi
+    if test -f ./Makefile ; then
+	${MAKE}
+      if test ${?} -ne 0; then
+	error "make failed for package '${pkg_name}'"
+	do_exit_on_error
+      fi
+      if ${clean}; then
+	${MAKE} clean
+      fi
+      return
+    fi
+  fi
+  if test "$Type" = "Translation" ; then
+    message "Installing *Translation* package '${pkg_name}' ..."
+    if test -d "share"; then
+      cp -r ./share ${R_HOME}
+    fi
+    if test -d "library"; then
+      cp -r ./library ${R_HOME}
+    fi
+    return
+  fi
+
   if test "${pkg_name}" = "${R_PACKAGE_NAME}"; then
     message "Installing *source* package '${pkg_name}' ..."
   else
@@ -403,7 +478,7 @@ do_install_source () {
 
   if test -f "${R_PACKAGE_DIR}/DESCRIPTION"; then
     ## Back up previous version.
-    if ${lock} ; then 
+    if ${lock} ; then
       mv "${R_PACKAGE_DIR}" "${lockdir}/${R_PACKAGE_NAME}"
     else
       ## this is only used for recommended packages installed from .tgz
@@ -420,6 +495,10 @@ do_install_source () {
     fi
     ## check if we are in a bundle so we can back out the whole bundle
     if grep "^Bundle:" DESCRIPTION >/dev/null; then
+      if ${tar_up} ; then
+        error "cannot build (nor INSTALL) binary versions of bundles"
+        do_exit_on_error
+      fi
       bundlepkg=`get_dcf_field Contains ../DESCRIPTION`
     else
       bundlepkg=${pkg_name}
@@ -434,6 +513,7 @@ do_install_source () {
     fi
   fi
 
+
   for f in COPYING NAMESPACE; do
     if test -f "${f}"; then
       cp "${f}" "${R_PACKAGE_DIR}"
@@ -443,7 +523,7 @@ do_install_source () {
 
   ## Install DESCRIPTION file with build information.
   echo "tools:::.install_package_description(\".\", \"${R_PACKAGE_DIR}\")" | \
-    R_DEFAULT_PACKAGES=NULL LANG=C "${R_EXE}" --vanilla >/dev/null
+    R_DEFAULT_PACKAGES=NULL LC_ALL=C "${R_EXE}" --vanilla >/dev/null
   if test ${?} -ne 0; then
     error "installing package DESCRIPTION failed"
     do_exit_on_error
@@ -457,6 +537,11 @@ do_install_source () {
     if test -f src/Makefile; then
       cd src;
       makefiles="-f \"${R_HOME}\"/share/make/shlib.mk -f Makefile"
+      if test -r "${HOME}/.R/Makevars-${R_PLATFORM}"; then
+	  makefiles="${makefiles} -f \"${HOME}/.R/Makevars-${R_PLATFORM}\""
+      elif test -r "${HOME}/.R/Makevars"; then
+	  makefiles="${makefiles} -f \"${HOME}/.R/Makevars\""
+      fi
       if test -r Makevars; then
 	makefiles="-f Makevars ${makefiles}"
       fi
@@ -489,14 +574,14 @@ do_install_source () {
       ${MKDIR_P} "${R_PACKAGE_DIR}/R"
       rm -f "${R_PACKAGE_DIR}/R/"*
       echo "tools:::.install_package_code_files(\".\", \"${R_PACKAGE_DIR}\")" | \
-        R_DEFAULT_PACKAGES=NULL LANG=C "${R_EXE}" --vanilla >/dev/null
+        R_DEFAULT_PACKAGES=NULL LC_ALL=C "${R_EXE}" --vanilla >/dev/null
       if test ${?} -ne 0; then
         error "unable to collate files for package '${pkg_name}'"
         do_exit_on_error
       fi
     if test -f "R/sysdata.rda"; then
       echo "tools:::sysdata2LazyLoadDB(\"R/sysdata.rda\", \"${R_PACKAGE_DIR}/R\")" | \
-        R_DEFAULT_PACKAGES=NULL LANG=C "${R_EXE}" --vanilla > /dev/null ; \
+        R_DEFAULT_PACKAGES=NULL LC_ALL=C "${R_EXE}" --vanilla > /dev/null ; \
       if test ${?} -ne 0; then \
         error "unable to build sysdata DB for package '${pkg_name}'" ; \
         do_exit_on_error ; \
@@ -518,7 +603,6 @@ do_install_source () {
     ${MKDIR_P} "${R_PACKAGE_DIR}/data"
     rm -f "${R_PACKAGE_DIR}/data/"*
     cp data/* "${R_PACKAGE_DIR}/data" 2>/dev/null
-    rm -f "${R_PACKAGE_DIR}/data/datalist"
     chmod 644 "${R_PACKAGE_DIR}/data/"*
     parse_description_field LazyData
     if test "$value" = "missing" ; then
@@ -532,7 +616,7 @@ do_install_source () {
       ## code in the package, so ensure the package we have just
       ## installed is on the library path.
       echo "invisible(.libPaths(c(\"${lib}\", .libPaths()))); tools:::data2LazyLoadDB(\"${R_PACKAGE_NAME}\", \"${lib}\")" | \
-        R_DEFAULT_PACKAGES=NULL LANG=C "${R_EXE}" --vanilla > /dev/null
+        R_DEFAULT_PACKAGES=NULL LC_ALL=C "${R_EXE}" --vanilla > /dev/null
     if test ${?} -ne 0; then
       error "lazydata failed for package '${pkg_name}'"
       do_exit_on_error
@@ -620,7 +704,7 @@ do_install_source () {
       if test -s R_PROFILE.R; then cat R_PROFILE.R; fi; \
       echo "invisible(.libPaths(c(\"${lib}\", .libPaths()))); .getRequiredPackages()"; \
       ${code_cmd}) | \
-        R_DEFAULT_PACKAGES= LANG=C "${R_EXE}" ${R_save_args} ${save_args}
+        R_DEFAULT_PACKAGES= LC_ALL=C "${R_EXE}" ${R_save_args} ${save_args}
     if test ${?} -ne 0; then
       error "execution of package source for '${pkg_name}' failed"
       do_exit_on_error
@@ -646,9 +730,9 @@ do_install_source () {
   if test ! -d R ; then
     thislazy=false
   fi
-  ## this test is designed to fail if a loader is used.
-  ## beware: the wc format is not portable -- some systems give
-  ## size in a left-space-padded first field, and some do not pad. 
+  ## This test is designed to fail if a loader is used.
+  ## Beware: the wc format is not portable -- some systems give
+  ## size in a left-space-padded first field, and some do not pad.
   if test "x$thislazy" = "xauto" ; then
     Rcodesize=`cat ${R_PACKAGE_DIR}/R/${pkg_name} | wc -c`
     if test ${Rcodesize} -gt 25000 ; then
@@ -661,7 +745,7 @@ do_install_source () {
     message "preparing package for lazy loading"
     (if test -s R_PROFILE.R; then cat R_PROFILE.R; fi; \
     echo "tools:::makeLazyLoading(\"${R_PACKAGE_NAME}\", \"${lib}\")") | \
-      R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_EXE}" --vanilla --slave
+      R_DEFAULT_PACKAGES= LC_ALL=C "${R_EXE}" --vanilla --slave
     if test ${?} -ne 0; then
       error "lazy loading failed for package '${pkg_name}'"
       do_exit_on_error
@@ -723,8 +807,9 @@ do_install_source () {
     echo "No man pages found in package '${pkg_name}'"
   fi
 
+  message "building package indices ..."
   echo "invisible(.libPaths(c(\"${lib}\", .libPaths()))); tools:::.install_package_indices(\".\", \"${R_PACKAGE_DIR}\")" | \
-    R_DEFAULT_PACKAGES=NULL LANG=C "${R_EXE}" --vanilla >/dev/null
+    R_DEFAULT_PACKAGES=NULL LC_ALL=C "${R_EXE}" --vanilla >/dev/null
   if test ${?} -ne 0; then
     error "installing package indices failed"
     do_exit_on_error
@@ -733,7 +818,7 @@ do_install_source () {
   ## Install a dump of the parsed NAMESPACE file
   if test -f NAMESPACE && test "${fake}" != "true"; then
       echo "tools:::.install_package_namespace_info(\".\", \"${R_PACKAGE_DIR}\")" | \
-        R_DEFAULT_PACKAGES=NULL LANG=C "${R_EXE}" --vanilla >/dev/null
+        R_DEFAULT_PACKAGES=NULL LC_ALL=C "${R_EXE}" --vanilla >/dev/null
     if test ${?} -ne 0; then
       error "installing namespace metadata failed"
       do_exit_on_error
@@ -744,8 +829,7 @@ do_install_source () {
   ## Remove stuff we should not have installed in the first place.
   ## When installing from a source directory under CVS control, we
   ## should really exclude the CVS subdirs.  The same applies for the
-  ## .svn Subversion subdirs.  (In fact, we should also exclude
-  ## everything in @file{.Rbuildignore}, but that's another story ...)
+  ## .svn Subversion subdirs.
   find "${R_PACKAGE_DIR}" -name CVS -type d -prune \
     -exec rm -rf \{\} \; 2>/dev/null
   find "${R_PACKAGE_DIR}" -name .svn -type d -prune \
@@ -766,6 +850,17 @@ do_install_source () {
     if test -x ./cleanup ; then
       ./cleanup
     fi
+  fi
+
+  ## now repackage as a tarball if requested
+  if ${tar_up} ; then
+    version=`get_dcf_field Version DESCRIPTION`
+    ## R_PLATFORM is set by R CMD
+    filename="${R_PACKAGE_NAME}_${version}_R_${R_PLATFORM}.tar"
+    filepath="${startdir}/$filename"
+    ${TAR} -chf "$filepath" -C "${R_LIBRARY_DIR}" ${R_PACKAGE_NAME}
+    ${R_GZIPCMD} -9f "$filepath"
+    echo "packaged installation of '${R_PACKAGE_NAME}' as ${filename}.gz"
   fi
 
   stars="*"
@@ -838,7 +933,7 @@ do_install () {
   if grep "^Built:" DESCRIPTION >/dev/null ; then
     ## If DESCRIPTION has a @samp{Built:} entry this is a binary
     ## package.  This is the right test, but not available for packages
-    ## installed prior to 1.4.0 -- but 2.0.0 requires packages to be 
+    ## installed prior to 1.4.0 -- but 2.0.0 requires packages to be
     ## reinstalled.
     is_source_package=false
   else
@@ -889,14 +984,10 @@ do_exit_on_error () {
 }
 
 do_cleanup () {
-  ## Solaris will not remove any directory in the current path
-  cd "${startdir}"
-  if test -d "${tmpdir}"; then
-    rm -rf "${tmpdir}"
-  fi
+  do_cleanup_tmpdir
 
   if test "${is_first_package}" = no; then
-    ## Only need to do this in case we successfully installed  at least
+    ## Only need to do this in case we successfully installed at least
     ## *one* package ... well not so sure for bundles.
     cp "${R_HOME}/doc/html/R.css" "${lib}"
     chmod 644 "${lib}/R.css"
