adding v1.2.0

diff --git a/src/scripts/INSTALL.in b/src/scripts/INSTALL.in
--- a/src/scripts/INSTALL.in
+++ b/src/scripts/INSTALL.in
@@ -4,11 +4,15 @@
 
 # @configure_input@
 
-revision='$Revision: 1.40.2.2 $'
+revision='$Revision: 1.52 $'
 version=`set - ${revision}; echo ${2}`
-version="R add-on package installer ${version}"
+version="R add-on package installer ${version}
 
-usage="Usage: R INSTALL [options] pkgs
+Copyright (C) 2000 The R Core Development Team.
+This is free software; see the GNU General Public Licence version 2
+or later for copying conditions.  There is NO warranty."
+
+usage="Usage: R CMD INSTALL [options] pkgs
 
 Install the add-on packages specified by pkgs into the default R library
 tree (${R_HOME}/library) or the tree specified via \`--library'.  The
@@ -16,17 +20,20 @@ elements of pkgs can be relative or absolute paths to directories with
 the package (bundle) sources, or to gzipped package \`tar' archives.
 
 Options:
+  -h, --help		print short help message and exit
+  -v, --version		print version info and exit
+      --configure-args=ARGS
+                        set args for package's configure script (if any)
   -c, --clean		remove all files created during installation
   -d, --debug		turn on shell and build-help debugging
-  -h, --help		print short help message and exit
   -l, --library=LIB	install packages to library tree LIB
+      --no-configure    do not use the package's configure script
       --no-docs		do not build and install documentation
       --use-zip-data	collect data files in zip archive
       --use-zip-help	collect help and examples into zip archives
       --use-zip		combine \`--use-zip-data' and \`--use-zip-help'
-  -v, --version		print version info and exit
 
-Report bugs to <R-bugs@lists.r-project.org>."
+Report bugs to <r-bugs@r-project.org>."
 
 R_VERSION='@VERSION@'
 INSTALL='@INSTALL@'
@@ -39,7 +46,7 @@ NO_PERL5_MSG="\
 *** get the PDF reference manual from the nearest CRAN server.
 *** The CRAN master site can be found at
 ***    http://cran.r-project.org/"
-tmpdir="${TMPDIR:-/tmp}/R.INSTALL.$$"
+tmpdir="${TMPDIR-/tmp}/R.INSTALL.$$"
 
 umask 022
 
@@ -79,6 +86,7 @@ build_latex=true
 build_example=true
 build_help=true
 build_help_opts=
+use_configure=true
 use_zip_data=
 use_zip_help=
 
@@ -92,6 +100,8 @@ while test -n "${1}"; do
       clean=true ;;
     -d|--debug)
       debug=true ;;
+    --no-configure)
+      use_configure=false ;;
     --no-docs)
       build_text=false
       build_html=false
@@ -190,134 +200,160 @@ do_install () {
   fi
 
   mkdir -p ${lib}/${pkg} || exit 3
-  echo "Installing package \`${pkg}' ..."
-
-  if test -x ./configure ; then
-    ./configure ${configure_args}
-    if test ${?} -ne 0; then
-      echo "ERROR: Configuration failed for package \`${pkg}'"
-      exit 4
-    fi
-  fi
-
-  if test -d src; then
-    echo " libs"
-    if ${debug}; then set -x; fi
-    mkdir -p ${lib}/${pkg}/libs
-    if test -f src/Makefile; then
-      (cd src;
-        makefiles="-f ${R_HOME}/etc/Makeconf -f Makefile"
-	if test -r Makevars; then
-	  makefiles="-f Makevars ${makefiles}"
-	fi
-	${MAKE} ${makefiles} \
-	  && cp *.@SHLIBEXT@ ${lib}/${pkg}/libs \
-	  || error=true; \
-	if ${clean}; then ${MAKE} clean; fi)
-    else
-      (cd src;
-        srcs=`ls *.[cf] *.cc 2>/dev/null`
-	sh ${R_HOME}/bin/SHLIB \
-	    -o ${lib}/${pkg}/libs/${pkg}.@SHLIBEXT@ ${srcs} \
-	  || error=true; \
-	if ${clean}; then rm -f *.o; fi)
-    fi
-    if ${error}; then
-      echo "ERROR: Compilation failed for package \`${pkg}'"
-      exit 5
-    fi
-    if ${debug}; then set +x; fi
-  fi
-
-  if test -d R; then dir=R; elif test -d funs; then dir=funs; fi
-  if test "${dir}"; then
-    echo " ${dir}"
-    mkdir -p ${lib}/${pkg}/R
-    cat `ls ${dir}/*.[RSqrs] ${dir}/unix/*.[RSqrs] 2>/dev/null` \
-      > ${lib}/${pkg}/R/${pkg}
-  fi
-  dir=
-
-  if test -d data; then
-    echo " data"
-    mkdir -p ${lib}/${pkg}/data
-    cp data/* ${lib}/${pkg}/data
-    chmod 644 ${lib}/${pkg}/data/*
-    if test -n "${use_zip_data}" \
-        -a -n "${R_UNZIPCMD}" \
-        -a -n "${R_ZIPCMD}"; then
-      (cd ${lib}/${pkg}/data;
-        find . -type f -print > filelist
-        ${R_ZIPCMD} -m Rdata * -x filelist 00Index)
-    fi
-  fi
-
-  if test -d exec; then
-    echo " exec"
-    mkdir -p ${lib}/${pkg}/exec
-    cp exec/* ${lib}/${pkg}/exec
-    chmod 755 ${lib}/${pkg}/exec/*
-  fi
-
-  if test -d inst; then
-    echo " inst"
-    cp -r inst/* ${lib}/${pkg}
-  fi
-
-  for f in COPYING DESCRIPTION INDEX; do
-    if test -f ${f}; then cp ${f} ${lib}/${pkg}; fi
-  done
-  title=`grep -s "^Title:" DESCRIPTION | sed "s/^Title:[ \t]*//"`
-  if test "${title}"; then
-      ${R_HOME}/bin/maketitle > ${lib}/${pkg}/TITLE
-  elif test -f TITLE; then
-    cp TITLE ${lib}/${pkg}
-  fi
-  (cd ${lib}; cat */TITLE > LibIndex 2> /dev/null)
 
   if test -d man; then
-    echo " help"
-    if ${build_help}; then
-      if ${NO_PERL5}; then
-	echo "${NO_PERL5_MSG}"
+    ## Assume this is a source package.
+    ## FIXME:  Do we have a better test?
+    echo "Installing source package \`${pkg}' ..."
+
+    ## Make the destination directories available to the developer's
+    ## installation scripts (e.g. configure, etc.)
+    R_PACKAGE_DIR=${lib}/${pkg}
+    R_LIBRARY_DIR=${lib}
+    R_PACKAGE_NAME=${pkg}
+    export R_LIBRARY_DIR
+    export R_PACKAGE_DIR
+    export R_PACKAGE_NAME
+
+    if ${use_configure} && test -x ./configure ; then
+      ./configure ${configure_args}
+      if test ${?} -ne 0; then
+	echo "ERROR: Configuration failed for package \`${pkg}'"
+	exit 4
+      fi
+    fi
+
+    if test -d src; then
+      echo " libs"
+      if ${debug}; then set -x; fi
+      mkdir -p ${lib}/${pkg}/libs
+      if test -f src/Makefile; then
+        cd src;
+          makefiles="-f ${R_HOME}/etc/Makeconf -f Makefile"
+	  if test -r Makevars; then
+	    makefiles="-f Makevars ${makefiles}"
+	  fi
+	  ${MAKE} ${makefiles} \
+	    && cp *.@SHLIB_EXT@ ${lib}/${pkg}/libs \
+	    || error=true; \
+	  if ${clean}; then
+	    ${MAKE} clean
+	  fi
+	cd ..
       else
-	if ${debug}; then
-	  echo "  ${R_HOME}/bin/build-help ${BUILD_HELP_OPTS} ../${pkg} ${lib}"
-	fi
-	${R_HOME}/bin/build-help ${build_help_opts} ../${pkg} ${lib}
-	${R_HOME}/bin/Rd2contents ../${pkg} > ${lib}/${pkg}/CONTENTS
-	if test ${lib} = ${R_HOME}/library; then 
-	  ${R_HOME}/bin/build-help --htmllists
-	  cat ${R_HOME}/library/*/CONTENTS \
-	    > ${R_HOME}/doc/html/search/index.txt
-	fi	
+        cd src;
+          srcs=`ls *.[cfC] *.cc *.cpp 2>/dev/null`
+	  sh ${R_HOME}/bin/SHLIB -o ${pkg}.@SHLIB_EXT@ ${srcs} \
+	    && cp *.@SHLIB_EXT@ ${lib}/${pkg}/libs \
+  	    || error=true; \
+	  if ${clean}; then
+	    rm -f .libs _libs *.o *.@SHLIB_EXT@
+	  fi
+	cd ..
       fi
-      if test -n "${use_zip_help}" \
-	  -a -n "${R_UNZIPCMD}" \
-	  -a -n "${R_ZIPCMD}"; then
-	cd ${lib}/${pkg}
-	if test -d R-ex; then
-	  (cd R-ex; ${R_ZIPCMD} -m Rex *.R)
-	fi
-	## NOT YET:
-	## if test -d latex; then
-	##   (cd latex; ${R_ZIPCMD} -m Rhelp *.tex)
-	## fi
-	if test -d help; then
-	  (cd help; ${R_ZIPCMD} -m Rhelp * -x 00Titles AnIndex);
-	fi
+      if ${error}; then
+	echo "ERROR: Compilation failed for package \`${pkg}'"
+	exit 5
+      fi
+      if ${debug}; then set +x; fi
+    fi
+
+    if test -d R; then
+      echo " R"
+      mkdir -p ${lib}/${pkg}/R
+      cat `ls R/*.[RSqrs] R/unix/*.[RSqrs] 2>/dev/null` \
+	> ${lib}/${pkg}/R/${pkg}
+    fi
+
+    if test -d data; then
+      echo " data"
+      mkdir -p ${lib}/${pkg}/data
+      cp data/* ${lib}/${pkg}/data
+      chmod 644 ${lib}/${pkg}/data/*
+      if test -n "${use_zip_data}" \
+          -a -n "${R_UNZIPCMD}" \
+          -a -n "${R_ZIPCMD}"; then
+        (cd ${lib}/${pkg}/data;
+          find . -type f -print > filelist
+          ${R_ZIPCMD} -m Rdata * -x filelist 00Index)
       fi
     fi
-  else
-    echo "  No man pages found in package \`${pkg}'"
-  fi
 
-  if ${clean}; then
-    if test -x ./cleanup ; then
-      ./cleanup
+    if test -d exec; then
+      echo " exec"
+      mkdir -p ${lib}/${pkg}/exec
+      cp exec/* ${lib}/${pkg}/exec
+      chmod 755 ${lib}/${pkg}/exec/*
     fi
+
+    if test -d inst; then
+      echo " inst"
+      cp -r inst/* ${lib}/${pkg}
+    fi
+
+    for f in COPYING DESCRIPTION INDEX; do
+      if test -f ${f}; then cp ${f} ${lib}/${pkg}; fi
+    done
+    title=`grep -s "^Title:" DESCRIPTION | sed "s/^Title:[ \t]*//"`
+    if test "${title}"; then
+      ${R_HOME}/bin/maketitle > ${lib}/${pkg}/TITLE
+    elif test -f TITLE; then
+      cp TITLE ${lib}/${pkg}
+    fi
+    ## stamp DESCRIPTION with build information
+    echo "Built: R" ${R_VERSION}\;  ${R_PLATFORM}\;  `date` \
+      >> ${lib}/${pkg}/DESCRIPTION
+
+    if test -d man; then
+      echo " help"
+      if ${build_help}; then
+	if ${NO_PERL5}; then
+	  echo "${NO_PERL5_MSG}"
+	else
+	  if ${debug}; then
+	    echo "  ${R_HOME}/bin/build-help ${BUILD_HELP_OPTS} ../${pkg} ${lib}"
+	  fi
+	  ${R_HOME}/bin/build-help ${build_help_opts} ../${pkg} ${lib}
+	  ${R_HOME}/bin/Rd2contents ../${pkg} > ${lib}/${pkg}/CONTENTS
+	  if test ${lib} = ${R_HOME}/library; then 
+	    ${R_HOME}/bin/build-help --htmllists
+	    cat ${R_HOME}/library/*/CONTENTS \
+	      > ${R_HOME}/doc/html/search/index.txt
+	  fi	
+	fi
+	if test -n "${use_zip_help}" \
+            -a -n "${R_UNZIPCMD}" \
+	    -a -n "${R_ZIPCMD}"; then
+	  cd ${lib}/${pkg}
+	  if test -d R-ex; then
+	    (cd R-ex; ${R_ZIPCMD} -m Rex *.R)
+	  fi
+	  ## NOT YET:
+	  ## if test -d latex; then
+	  ##   (cd latex; ${R_ZIPCMD} -m Rhelp *.tex)
+	  ## fi
+	  if test -d help; then
+	    (cd help; ${R_ZIPCMD} -m Rhelp * -x 00Titles AnIndex);
+	  fi
+        fi
+      fi
+    else
+      echo "  No man pages found in package \`${pkg}'"
+    fi
+
+    if ${clean}; then
+      if test -x ./cleanup ; then
+	./cleanup
+      fi
+    fi
+
+  else  
+    ## Assume this is a binary package
+    echo "Installing binary package \`${pkg}' ..."
+    cp -r . ${lib}/${pkg}
   fi
 
+  (cd ${lib}; cat */TITLE > LibIndex 2> /dev/null)  
   chmod -R a+r ${lib}/${pkg}
 
   echo " DONE (${pkg})"
