adding v1.0.0

diff --git a/src/scripts/INSTALL.in b/src/scripts/INSTALL.in
--- a/src/scripts/INSTALL.in
+++ b/src/scripts/INSTALL.in
@@ -4,7 +4,7 @@
 
 # @configure_input@
 
-revision='$Revision: 1.30 $'
+revision='$Revision: 1.34 $'
 version=`set - ${revision}; echo ${2}`
 version="R add-on package installer ${version}"
 
@@ -144,7 +144,7 @@ else
 fi
 
 if ${build_text}; then
-  build_help_opts="${build_help_opts} --nroff"
+  build_help_opts="${build_help_opts} --txt"
 fi
 if ${build_html}; then
   build_help_opts="${build_help_opts} --html"
@@ -184,6 +184,10 @@ do_install () {
 
   if test -x ./configure ; then
     ./configure ${configure_args}
+    if test ${?} -ne 0; then
+      echo "ERROR: Configuration failed for package \`${pkg}'"
+      exit 4
+    fi
   fi
 
   if test -d src; then
@@ -209,7 +213,7 @@ do_install () {
     fi
     if ${error}; then
       echo "ERROR: Compilation failed for package \`${pkg}'"
-      exit 4
+      exit 5
     fi
     if ${debug}; then set +x; fi
   fi
@@ -242,20 +246,15 @@ do_install () {
     cp -r inst/* ${lib}/${pkg}
   fi
 
-  if test -f DESCRIPTION; then
-    cp DESCRIPTION ${lib}/${pkg}
-  fi
-  if test -f INDEX; then
-    cp INDEX ${lib}/${pkg}
-  fi
-  if test -f TITLE; then
-    cp TITLE ${lib}/${pkg}
-  else
-    title=`grep -s "^Title:" DESCRIPTION | sed "s/^Title:[ \t]*//"`
-    if test "${title}"; then
+  for f in COPYING DESCRIPTION INDEX; do
+    if test -f ${f}; then cp ${f} ${lib}/${pkg}; fi
+  done
+  title=`grep -s "^Title:" DESCRIPTION | sed "s/^Title:[ \t]*//"`
+  if test "${title}"; then
       ${R_HOME}/bin/maketitle > ${lib}/${pkg}/TITLE
-    fi
-  fi  
+  elif test -f TITLE; then
+    cp TITLE ${lib}/${pkg}
+  fi
   (cd ${lib}; cat */TITLE > LibIndex 2> /dev/null)
 
   if test -d man; then
diff --git a/src/scripts/R.sh.in b/src/scripts/R.sh.in
--- a/src/scripts/R.sh.in
+++ b/src/scripts/R.sh.in
@@ -69,7 +69,8 @@ Options:
   --silent              Same as --quiet
   --slave               Make R run as quietly as possible
   --verbose             Print more information about progress
-  -d, --debugger=NAME   Run R through debugger NAME
+  -d NAME, --debugger=NAME
+                        Run R through debugger NAME
   --gui=TYPE		Use TYPE as GUI; possible values are \`X11'
 			(default) and \`GNOME'
 
@@ -101,7 +102,7 @@ debugger=
 gui=X11
 while test -n "${1}"; do
   case ${1} in
-    RHOME)
+    RHOME|--print-home)
       echo ${R_HOME}; exit 0 ;;
     BATCH|COMPILE|INSTALL|REMOVE|SHLIB)
       cmd="${1}"; shift; exec sh "${R_HOME}/bin/${cmd}" "${@}" ;;
@@ -111,10 +112,24 @@ while test -n "${1}"; do
       echo "option \`${1}' is defunct, use \`--gui=GNOME'"
       exit 1
       ;;
+    --gui)
+      if test -n "`echo ${2} | sed 's/^-.*//'`"; then
+	gui="${2}"; shift
+      else
+	echo "ERROR: option \`${1}' requires an argument"
+	exit 1
+      fi
+      ;;
     --gui=*)
       gui=`echo "${1}" | sed -e 's/[^=]*=//'` ;;
-    -d)
-      debugger="${2}"; shift ;;
+    -d|--debugger)
+      if test -n "`echo ${2} | sed 's/^-.*//'`"; then      
+	debugger="${2}"; shift
+      else
+	echo "ERROR: option \`${1}' requires an argument"
+	exit 1
+      fi
+      ;;
     --debugger=*)
       debugger=`echo "${1}" | sed -e 's/[^=]*=//'` ;;
     --no-environ)
@@ -131,6 +146,12 @@ while test -n "${1}"; do
   esac
   shift
 done
+
+# R_HOME may have moved, so check (or you get "GUI X11 is not supported")
+if [ ! -x ${R_HOME} ]; then
+  echo "R_HOME = \`${R_HOME}' not found"
+  exit 1
+fi
 
 if test -x ${R_HOME}/bin/R.${gui}; then
   R_binary="R.${gui}"
