adding v2.15.3

diff --git a/src/scripts/javareconf b/src/scripts/javareconf
--- a/src/scripts/javareconf
+++ b/src/scripts/javareconf
@@ -1,15 +1,16 @@
 if test -z "${R_HOME}"; then
-    echo "This command can be executed via R CMD only!"
+    echo "This command can be only executed via R CMD!"
     exit 1
 fi
 
+DYLIB_EXT=`${R_HOME}/bin/R CMD config DYLIB_EXT`
 tools_classpath=${R_SHARE_DIR}/java
 
-revision='$Rev: 59038 $'
+revision='$Rev: 62021 $'
 version=`set - ${revision}; echo ${2}`
 version="R Java configurator: ${R_VERSION} (r${version})
 
-Copyright (C) 2002-11 The R Core Team.
+Copyright (C) 2002-13 The R Core Team.
 This is free software; see the GNU General Public License version 2
 or later for copying conditions.  There is NO warranty."
 
@@ -22,7 +23,7 @@ Options:
   -h, --help     print this help message and exit
   -v, --version  print version info and exit
   -n, --dry-run  perform Java detection, but don't touch any
-                 configurations files
+                 configuration files
   -e <prog>      same as -n but exports all detected variables
                  and runs <prog>. If -e is the last argument
                  or <prog> is '' then a shell is used instead
@@ -196,11 +197,12 @@ custom_JAVA_LD_LIBRARY_PATH="${JAVA_LD_LIBRARY_PATH}"
 
 # sys-dependent tweaks to JNI flags
 hostos=`uname 2>/dev/null`
+## NB: that is not the same name as in configuration.
 case "$hostos" in
     Darwin*)
 	JAVA_LD_LIBRARY_PATH=
 	JAVA_LIBS="-framework JavaVM"
-	JAVA_CPPFLAGS='-I$(JAVA_HOME)/include'
+        JAVA_CPPFLAGS="-I/System/Library/Frameworks/JavaVM.framework/Headers"
 	has_libjvm=unknown
 	;;
     *)
@@ -211,32 +213,25 @@ case "$hostos" in
 	export LD_LIBRARY_PATH
 	# remove trailing/leading : (if any)
 	java_library_path=`"$JAVA" -classpath "${tools_classpath}" getsp java.library.path| ${SED-sed} -e 's/:$//' -e 's/^://'`
-	# unfortunately recent Oracle Java distributions ship with broken
-	# java.library.path so we try to see if that is the case
+	## see if libjvm is on this path: it is not for recent Oracle Java
 	has_libjvm=no
 	save_IFS=$IFS; IFS=:
 	for dir in ${java_library_path}; do
-	    if test -f "$dir/libjvm.so"; then
+	    if test -f "$dir/libjvm${DYLIB_EXT}"; then
 		has_libjvm=yes
 		break
 	    fi
 	done
-	# for broken java.library.path try some heuristic using sun.boot.library.path
+	# Then try some heuristics using sun.boot.library.path
 	if test ${has_libjvm} = no; then
 	    echo "NOTE: Your JVM has a bogus java.library.path system property!" >&2
 	    echo "      Trying a heuristic via sun.boot.library.path to find jvm library..." >&2
 	    boot_path=`"$JAVA" -classpath "${tools_classpath}" getsp sun.boot.library.path| ${SED-sed} -e 's/:$//' -e 's/^://'`
 	    if test -n "${boot_path}"; then
 		for dir in "${boot_path}" "${boot_path}/client" "${boot_path}/server"; do
-		    if test -f "$dir/libjvm.so"; then
+		    if test -f "$dir/libjvm${DYLIB_EXT}"; then
 			has_libjvm=yes
-			# NOTE: we decided to ignore java.library.path altogether since it was bogus
-			#       we could just append the newly found paths, though
-			if test "${dir}" = "${boot_path}"; then
-			    java_library_path="${dir}"
-			else
-			    java_library_path="${boot_path}:${dir}"
-			fi
+			java_library_path="${dir}"
 			break
 		    fi
 		done
@@ -270,6 +265,7 @@ case "$hostos" in
 	   host_os=`echo 'cat(R.version$os)'|${R_HOME}/bin/R --vanilla --slave 2>/dev/null`
            ## put the most probable locations for each system in the first place
            case "${host_os}" in
+             darwin*)  jmdirs=darwin;;
              linux*)   jmdirs=linux;;
              bsdi*)    jmdirs=bsdos;;
              osf*)     jmdirs=alpha;;
@@ -329,7 +325,7 @@ else
   if test "${acx_custom_java_libs}" = yes; then
     echo ''
     echo ' ** Warning: you are using custom JAVA_LIBS setting without' >&2
-    echo '    specifying JAVA_LD_LIBRARY_PATH. We cannot gearantee that' >&2
+    echo '    specifying JAVA_LD_LIBRARY_PATH. We cannot guarantee that' >&2
     echo '    this will work, both must match for a proper Java operation!' >&2
   fi
 fi
@@ -361,7 +357,13 @@ test "${dry_run}" = yes && exit 0
 
 echo "Updating Java configuration in ${R_HOME}"
 
-files="${R_HOME}/etc${R_ARCH}/Makeconf ${R_HOME}/etc${R_ARCH}/ldpaths"
+## We update both the base and arch-specific versions as etc/Makefile
+## copies the first to the second (only the second is used).
+if test -n "${R_ARCH}"; then
+  files="${R_HOME}/etc/Makeconf ${R_HOME}/etc/ldpaths ${R_HOME}/etc${R_ARCH}/Makeconf ${R_HOME}/etc${R_ARCH}/ldpaths"
+else
+  files="${R_HOME}/etc/Makeconf ${R_HOME}/etc/ldpaths"
+fi
 for file in $files; do
     ${SED-sed} -e "s|JAVA =.\{0,\}|JAVA = $JAVA|" -e "s|JAVA_HOME =.\{0,\}|JAVA_HOME = ${JAVA_HOME}|" -e "s|: \${JAVA_HOME=.\{1,\}|: \${JAVA_HOME=${JAVA_HOME}}|" -e "s|: \${R_JAVA_LD_LIBRARY_PATH=.\{1,\}|: \${R_JAVA_LD_LIBRARY_PATH=${JAVA_LD_LIBRARY_PATH_SH}}|" -e "s|JAVA_LIBS =.\{0,\}|JAVA_LIBS = ${JAVA_LIBS}|g" -e "s|JAVA_LD_LIBRARY_PATH =.\{0,\}|JAVA_LD_LIBRARY_PATH = ${JAVA_LD_LIBRARY_PATH}|" -e "s|JAVAC =.\{0,\}|JAVAC = $JAVAC|" -e "s|JAVAH =.\{0,\}|JAVAH = $JAVAH|" -e "s|JAR =.\{0,\}|JAR = $JAR|" -e "s|JAVA_CPPFLAGS =.\{0,\}|JAVA_CPPFLAGS = ${JAVA_CPPFLAGS}|g"  "${file}" > "${file}.new"
     if test -f "${file}.new"; then
