adding v2.8.1

diff --git a/src/scripts/Rd2dvi b/src/scripts/Rd2dvi
--- a/src/scripts/Rd2dvi
+++ b/src/scripts/Rd2dvi
@@ -7,7 +7,7 @@
 ##  R CMD Rd2dvi `grep -l "\\keyword{distr" \
 ##                  /path/to/Rsrc/src/library/stats/man/*.Rd | sort | uniq`
 
-revision='$Rev: 46686 $'
+revision='$Rev: 46964 $'
 version=`set - ${revision}; echo ${2}`
 version="Rd2dvi ${version}
 
@@ -43,6 +43,7 @@ Options:
       --pdf		generate PDF output
       --title=NAME	use NAME as the title of the document
   -V, --verbose		report on what is done
+      --no-index	don't index PDF output
 
 The output papersize is set by the environment variable R_PAPERSIZE.
 The DVI previewer is set by the environment variable xdvi.
@@ -61,6 +62,7 @@ out_ext="dvi"
 output=""
 verbose=false
 enc=unknown
+index=true
 
 if test "${R_OSTYPE}" = "windows"; then
   echo=echo
@@ -102,7 +104,7 @@ while test -n "${1}"; do
 	fi
       fi
       R_RD4DVI=${R_RD4PDF-"times,hyper"}
-      R_LATEXCMD=${PDFLATEX-pdflatex}
+      R_LATEXCMD="${R_PDFLATEXCMD}"
       ;;
     --title=*)
       title=`echo "${1}" | ${SED} -e 's/[^=]*=//'` ;;
@@ -110,7 +112,7 @@ while test -n "${1}"; do
       if test -n "`echo ${2} | ${SED} 's/^-.*//'`"; then      
 	output="${2}"; shift
       else
-	${echo} "ERROR: option '${1}' requires an argument"
+	echo "ERROR: option '${1}' requires an argument"
 	exit 1
       fi
       ;;
@@ -126,7 +128,9 @@ while test -n "${1}"; do
       build_dir=`echo "${1}" | ${SED} -e 's/[^=]*=//'` ;;
     -V|--verbose)
       verbose=${echo} ;;
-    --|*)
+     --no-index)
+      index=false ;;
+   --|*)
       break ;;
   esac
   shift
@@ -135,6 +139,16 @@ done
 if ${debug}; then set -x; fi
 
 . ${R_SHARE_DIR}/sh/dcf.sh	# get_dcf_field()
+
+
+do_cleanup () {
+  if ${clean}; then
+    cd ${start_dir}
+    rm -rf ${build_dir}
+  else
+    echo "You may want to clean up by 'rm -rf ${build_dir}'"
+  fi
+}
 
 Rdconv_dir_or_files_to_LaTeX () {
   ## Convert Rd files in a dir or a list of Rd files to LaTeX, appending
@@ -180,13 +194,14 @@ Rd_DESCRIPTION_to_LaTeX () {
   fields=`${SED} '/^[ 	]/d; s/^\([^:]*\):.*$/\1/' $1`
   ${echo} "\\begin{description}"
   ${echo} "\\raggedright{}"
+  ## this throws warnings on Solaris sed as input is missing newline
   for f in `${echo} "${fields}" | ${SED} '/Package/d; /Bundle/d;'`; do
     text=`get_dcf_field ${f} ${1} | \
       tr '\n' ' ' | \
       ${SED} "s/\"\([^\"]*\)\"/\\\`\\\`\\1''/g
                   s/\\\\\\\\/\\\\\\\\textbackslash /g
                   s/{/\\\\\\\\{/g
-		  s/}/\\\\\\\\}/g"`
+		  s/}/\\\\\\\\}/g" 2>/dev/null`
     ff=`echo ${f} | ${SED} s/_/\\\\\\\\_/g`
     ${echo} "\\item[${ff}] \\AsIs{${text}}"
   done
@@ -264,7 +279,7 @@ if test -z "${output}"; then
   output="Rd2.${out_ext}"
 fi
 if test -f ${output}; then
-  ${echo} "file '${output}' exists; please remove first"
+  echo "file '${output}' exists; please remove first"
   exit 1
 fi
 if test -d ${build_dir}; then
@@ -391,23 +406,56 @@ fi
 
 echo "Creating ${out_ext} output from LaTeX ..."
 cd ${build_dir}
-## R_LATEXCMD is redefined above for --pdf
-${R_LATEXCMD} ${R_TEXOPTS} Rd2 || status=1
-${R_MAKEINDEXCMD-makeindex} Rd2
-${R_LATEXCMD} ${R_TEXOPTS} Rd2
 if test "${out_ext}" = pdf; then
-  ${R_LATEXCMD} ${R_TEXOPTS} Rd2
+  ${R_PDFLATEXCMD} ${R_TEXOPTS} Rd2 || status=1
+  if test $status -gt 0; then
+    echo "Error in running pdflatex command ('${R_PDFLATEXCMD}')"
+    do_cleanup
+    exit 1
+  fi
+  if test "${index}" != "false"; then
+    ## OK for R_MAKEINDEXCMD to fail.
+    ${R_MAKEINDEXCMD} Rd2
+    ${R_PDFLATEXCMD} ${R_TEXOPTS} Rd2 || status=1
+    if test $status -gt 0; then
+      echo "Error in running pdflatex command ('${R_PDFLATEXCMD}')"
+      do_cleanup
+      exit 1
+    fi
+  fi
+  ${R_PDFLATEXCMD} ${R_TEXOPTS} Rd2 || status=1
+  if test $status -gt 0; then
+    echo "Error in running pdflatex command ('${R_PDFATEXCMD}')"
+    do_cleanup
+    exit 1
+  fi
+else
+  ${R_LATEXCMD} ${R_TEXOPTS} Rd2 || status=1
+  if test $status -gt 0; then
+    echo "Error in running latex command ('${R_LATEXCMD}')"
+    do_cleanup
+    exit 1
+  fi
+  ## OK for R_MAKEINDEXCMD to fail.
+  ${R_MAKEINDEXCMD} Rd2
+  ${R_LATEXCMD} ${R_TEXOPTS} Rd2 || status=1
+  if test $status -gt 0; then
+    echo "Error in running latex command ('${R_LATEXCMD}')"
+    do_cleanup
+    exit 1
+  fi
+fi
+if test ! -f Rd2.${out_ext}; then
+  echo "Error: no output file was created"
+  do_cleanup
+  exit 1
 fi
 cd ${start_dir}
-${echo} "Saving output to '${output}' ..."
+echo "Saving output to '${output}' ..."
 cp ${build_dir}/Rd2.${out_ext} ${output}
 echo "Done"
 
-if ${clean}; then
-  rm -rf ${build_dir}
-else
-  ${echo} "You may want to clean up by 'rm -rf ${build_dir}'"
-fi
+do_cleanup
 ${preview} ${output}
 exit ${status}
 
