adding v2.0.1

diff --git a/src/library/Recommended/Makefile.in b/src/library/Recommended/Makefile.in
--- a/src/library/Recommended/Makefile.in
+++ b/src/library/Recommended/Makefile.in
@@ -69,8 +69,12 @@ distclean: clean
 	-@test -z "$(DISTCLEANFILES)" || rm -f $(DISTCLEANFILES)
 maintainer-clean: distclean
 
+## we need to check that the recommended packages have been downloaded.
 distdir: $(DISTFILES)
-	@for f in $(DISTFILES) `cd $(srcdir) && ls *.tar.gz *.tgz`; do \
+	@if test `cd $(srcdir) && ls *.tar.gz | wc -l` -eq 0 ; then \
+	  echo "ERROR: no recommended packages" || exit 1 ; \
+	fi
+	@for f in $(DISTFILES) `cd $(srcdir) && ls *.tar.gz`; do \
 	  test -f $(distdir)/$${f} \
 	    || ln $(srcdir)/$${f} $(distdir)/$${f} 2>/dev/null \
 	    || cp -p $(srcdir)/$${f} $(distdir)/$${f}; \
