adding v1.7.0

diff --git a/doc/manual/Makefile.in b/doc/manual/Makefile.in
--- a/doc/manual/Makefile.in
+++ b/doc/manual/Makefile.in
@@ -47,7 +47,12 @@ R_PAPERSIZE = @R_PAPERSIZE@
 R_RD4DVI = @R_RD4DVI@
 R_RD4PDF = @R_RD4PDF@
 
-pkgsrcs = $(R_PKGS_BASE:=-pkg.tex)
+texinputs_BASE = $(R_PKGS_BASE:=-pkg.tex)
+texinputs_RECOMMENDED = $(R_PKGS_RECOMMENDED_EXPANDED:=-pkg.tex)
+R_PKGS_refman = base methods tools @USE_RECOMMENDED_PACKAGES_TRUE@ grid
+refman_TEXINPUTS = $(R_PKGS_refman:=-pkg.tex)
+refman_DEPENDENCIES = version.tex $(top_srcdir)/share/texmf/Rd.sty
+fullrefman_TEXINPUTS = $(texinputs_BASE) @USE_RECOMMENDED_PACKAGES_TRUE@ $(texinputs_RECOMMENDED)
 
 texiincludes = version.texi $(srcdir)/R-defs.texi
 
@@ -85,7 +90,7 @@ docs: html
 	TEXINPUTS="$(srcdir):$$TEXINPUTS" $(TEXI2PDF) $<
 
 dvi: refman.dvi $(OBJECTS_DVI)
-refman.dvi: version.tex $(top_srcdir)/share/texmf/Rd.sty stamp-refman-dvi
+refman.dvi: $(refman_DEPENDENCIES) stamp-refman-dvi
 	@if test "$(LATEX)" = false; then \
 	  echo "ERROR: 'latex' needed but missing on your system."; \
 	  exit 1; \
@@ -100,7 +105,9 @@ refman.dvi: version.tex $(top_srcdir)/share/texmf/Rd.sty stamp-refman-dvi
 	  opt="$${R_RD4DVI-$(R_RD4DVI)}"; \
 	  echo "\\usepackage[$${opt}]{Rd}"; \
 	  cat $(srcdir)/refman.top; \
-	  for p in $(R_PKGS_BASE); do echo "\\input{$${p}-pkg.tex}"; done; \
+	  texinputs=`(for f in $(refman_TEXINPUTS); \
+	    do echo $${f}; done) | LC_COLLATE=C sort`; \
+	  for f in $${texinputs}; do echo "\\input{$${f}}"; done; \
 	  cat $(srcdir)/refman.bot) > refman.tex
 ## </NOTE>
 	@TEXINPUTS="$(top_srcdir)/share/texmf:$$TEXINPUTS" \
@@ -114,9 +121,9 @@ version.tex: Makefile $(top_srcdir)/date-stamp $(top_srcdir)/VERSION
 	@(v=`cat $(top_srcdir)/VERSION`; \
 	  v="$${v} (`sed 's|/|-|g' $(top_srcdir)/date-stamp`)"; \
 	  echo "$${v}") > $@
-stamp-refman-dvi: $(pkgsrcs)
+stamp-refman-dvi: $(refman_TEXINPUTS)
 	@touch $@
-$(pkgsrcs): FORCE $(top_srcdir)/share/perl/build-help.pl
+$(texinputs_BASE): FORCE $(top_srcdir)/share/perl/build-help.pl
 	@(pkg=`basename $@ -pkg.tex`; \
 	if $(PERL) $(top_srcdir)/tools/Rdnewer.pl \
 	    "$(top_srcdir)/src/library/$${pkg}" "$@"; then \
@@ -126,6 +133,46 @@ $(pkgsrcs): FORCE $(top_srcdir)/share/perl/build-help.pl
 	  $(PERL) $(top_srcdir)/tools/pkg2tex.pl $${pkg}; \
 	fi)
 FORCE:
+$(texinputs_RECOMMENDED): FORCE
+	@(pkg=`basename $@ -pkg.tex`; \
+	if find $@ -newer $(top_builddir)/library/$${pkg}/DESCRIPTION \
+	    -print 2> /dev/null | grep $@ > /dev/null; then :; else \
+	  echo "collecting LaTeX docs for package '$${pkg}' ..."; \
+	  RLIB="$(top_builddir)/library" \
+	    $(PERL) $(top_srcdir)/tools/pkg2tex.pl $${pkg}; \
+	fi)
+
+fullrefman.dvi: $(refman_DEPENDENCIES) stamp-fullrefman-dvi
+	@if test "$(LATEX)" = false; then \
+	  echo "ERROR: 'latex' needed but missing on your system."; \
+	  exit 1; \
+	fi
+	@echo "DVI/LaTeX documentation: full reference index ..."
+	@rm -f *.aux fullrefman.toc fullrefman.ind stamp-fullrefman-dvi
+	@(opt="$${R_PAPERSIZE-$(R_PAPERSIZE)}paper"; \
+	  echo "\\documentclass[$${opt}]{book}"; \
+	  opt="$${R_RD4DVI-$(R_RD4DVI)}"; \
+	  echo "\\usepackage[$${opt}]{Rd}"; \
+	  cat $(srcdir)/refman.top; \
+	  echo "\\part{}"; \
+	  texinputs=`(for f in $(refman_TEXINPUTS); \
+	    do echo $${f}; done) | LC_COLLATE=C sort`; \
+	  for f in $${texinputs}; do echo "\\input{$${f}}"; done; \
+	  echo "\\part{}"; \
+	  texinputs=`(for f in $(fullrefman_TEXINPUTS); \
+	    do echo $${f}; done) | LC_COLLATE=C sort`; \
+	  for f in $(refman_TEXINPUTS); do \
+	    texinputs=`echo "$${texinputs}" | sed "s/$${f}//"`; \
+	  done; \
+	  for f in $${texinputs}; do echo "\\input{$${f}}"; done; \
+	  cat $(srcdir)/refman.bot) > fullrefman.tex
+	@TEXINPUTS="$(top_srcdir)/share/texmf:$$TEXINPUTS" \
+	  $(LATEX) '\nonstopmode\input{fullrefman.tex}'
+	@-$(MAKEINDEX) fullrefman
+	@TEXINPUTS="$(top_srcdir)/share/texmf:$$TEXINPUTS" \
+	  $(LATEX) '\nonstopmode\input{fullrefman.tex}'
+	@touch stamp-fullrefman-dvi
+stamp-fullrefman-dvi: $(fullrefman_TEXINPUTS)
 
 $(OBJECTS_DVI): $(srcdir)/texinfo.tex
 R-admin.dvi: $(texiincludes)
@@ -134,8 +181,11 @@ R-exts.dvi: $(texiincludes)
 version.texi: Makefile $(top_srcdir)/VERSION $(top_srcdir)/date-stamp
 	@echo "creating $(subdir)/$@"
 	@(v=`sed 's/\([^ ]*\).*/\1/' $(top_srcdir)/VERSION`; \
+	  echo "@set VERSIONno $${v}" > $@; \
 	  v="$${v} (`sed 's|/|-|g' $(top_srcdir)/date-stamp`)"; \
-	  echo "@set VERSION $${v}" > $@)
+	  echo "@set VERSION $${v}" >> $@; \
+	  rwv=`$(PERL) $(top_srcdir)/src/gnuwin32/fixed/rwver.pl $(top_srcdir)/VERSION`; \
+	  echo "@set RWVERSION $${rwv}" >> $@ )
 R-intro.dvi: stamp-images-eps $(texiincludes)
 stamp-images-eps:
 	@if test "$(BUILDDIR_IS_SRCDIR)" = no ; then \
@@ -161,7 +211,7 @@ R-intro.info: $(texiincludes)
 R-lang.info: $(texiincludes)
 
 pdf: refman.pdf $(OBJECTS_PDF)
-refman.pdf: version.tex $(top_srcdir)/share/texmf/Rd.sty stamp-refman-pdf
+refman.pdf: $(refman_DEPENDENCIES) stamp-refman-pdf
 	@if test "$(PDFLATEX)" = false; then \
 	  echo "ERROR: 'pdflatex' needed but missing on your system."; \
 	  exit 1; \
@@ -176,7 +226,9 @@ refman.pdf: version.tex $(top_srcdir)/share/texmf/Rd.sty stamp-refman-pdf
 	  opt="$${R_RD4PDF-$(R_RD4PDF)}"; \
 	  echo "\\usepackage[$${opt}]{Rd}"; \
 	  cat $(srcdir)/refman.top; \
-	  for p in $(R_PKGS_BASE); do echo "\\input{$${p}-pkg.tex}"; done; \
+	  texinputs=`(for f in $(refman_TEXINPUTS); \
+	    do echo $${f}; done) | LC_COLLATE=C sort`; \
+	  for f in $${texinputs}; do echo "\\input{$${f}}"; done; \
 	  cat $(srcdir)/refman.bot) > refman.tex
 ## </NOTE>
 	@TEXINPUTS="$(top_srcdir)/share/texmf:$$TEXINPUTS" \
@@ -190,8 +242,44 @@ refman.pdf: version.tex $(top_srcdir)/share/texmf/Rd.sty stamp-refman-pdf
 	  pool_size=500000 max_strings=50000 \
 	  $(PDFLATEX) '\nonstopmode\input{refman.tex}'
 	@touch stamp-refman-pdf
-stamp-refman-pdf: $(pkgsrcs)
+stamp-refman-pdf: $(refman_TEXINPUTS)
 	@touch $@
+fullrefman.pdf: $(refman_DEPENDENCIES) stamp-fullrefman-pdf
+	@if test "$(PDFLATEX)" = false; then \
+	  echo "ERROR: 'pdflatex' needed but missing on your system."; \
+	  exit 1; \
+	fi
+	@echo "PDF/LaTeX documentation: full reference index ..."
+	@rm -f *.aux fullrefman.toc fullrefman.ind stamp-fullrefman-pdf
+	@(opt="$${R_PAPERSIZE-$(R_PAPERSIZE)}paper"; \
+	  echo "\\documentclass[$${opt}]{book}"; \
+	  opt="$${R_RD4PDF-$(R_RD4PDF)}"; \
+	  echo "\\usepackage[$${opt}]{Rd}"; \
+	  cat $(srcdir)/refman.top; \
+	  echo "\\part{}"; \
+	  texinputs=`(for f in $(refman_TEXINPUTS); \
+	    do echo $${f}; done) | LC_COLLATE=C sort`; \
+	  for f in $${texinputs}; do echo "\\input{$${f}}"; done; \
+	  echo "\\part{}"; \
+	  texinputs=`(for f in $(fullrefman_TEXINPUTS); \
+	    do echo $${f}; done) | LC_COLLATE=C sort`; \
+	  for f in $(refman_TEXINPUTS); do \
+	    texinputs=`echo "$${texinputs}" | sed "s/$${f}//"`; \
+	  done; \
+	  for f in $${texinputs}; do echo "\\input{$${f}}"; done; \
+	  cat $(srcdir)/refman.bot) > fullrefman.tex
+	@TEXINPUTS="$(top_srcdir)/share/texmf:$$TEXINPUTS" \
+	  pool_size=500000 max_strings=50000 dest_names_size=50000 \
+	  $(PDFLATEX) '\nonstopmode\input{fullrefman.tex}'
+	@-$(MAKEINDEX) fullrefman
+	@TEXINPUTS="$(top_srcdir)/share/texmf:$$TEXINPUTS" \
+	  pool_size=500000 max_strings=50000 dest_names_size=50000 \
+	  $(PDFLATEX) '\nonstopmode\input{fullrefman.tex}'
+	@TEXINPUTS="$(top_srcdir)/share/texmf:$$TEXINPUTS" \
+	  pool_size=500000 max_strings=50000 dest_names_size=50000 \
+	  $(PDFLATEX) '\nonstopmode\input{fullrefman.tex}'
+	@touch stamp-fullrefman-pdf
+stamp-fullrefman-pdf: $(fullrefman_TEXINPUTS)
 
 $(OBJECTS_PDF): $(srcdir)/texinfo.tex $(srcdir)/pdfcolor.tex
 R-admin.pdf: $(texiincludes)
diff --git a/tests/Examples/Makefile.in b/tests/Examples/Makefile.in
--- a/tests/Examples/Makefile.in
+++ b/tests/Examples/Makefile.in
@@ -15,11 +15,14 @@ DISTFILES = Makefile.in
 
 R = $(top_builddir)/bin/R --vanilla
 
-EX_IN = $(R_PKGS_BASE:=-Ex.R)
-EX_OUT = $(EX_IN:.R=.Rout)
+EX_IN_BASE = $(R_PKGS_BASE:=-Ex.R)
+EX_OUT_BASE = $(EX_IN_BASE:.R=.Rout)
 
-RECOMMENDED_EX_IN = $(R_PKGS_RECOMMENDED_EXPANDED:=-Ex.R)
-RECOMMENDED_EX_OUT = $(RECOMMENDED_EX_IN:.R=.Rout)
+EX_IN_RECOMMENDED = $(R_PKGS_RECOMMENDED_EXPANDED:=-Ex.R)
+EX_OUT_RECOMMENDED = $(EX_IN_RECOMMENDED:.R=.Rout)
+
+RDIFF = $(top_builddir)/bin/R CMD Rdiff
+RVAL_IF_DIFF = 0
 
 .SUFFIXES:
 .SUFFIXES: .R .Rout
@@ -43,32 +46,63 @@ Makedeps: Makefile
 test-Examples: test-Examples-Base
 test-Examples-Base: Makefile
 	@$(MAKE) Makedeps
-	@$(MAKE) $(EX_OUT)
+	@$(MAKE) $(EX_OUT_BASE)
 
+## <NOTE>
+## We do *not* want this to be added to test-Examples conditional on
+## @USE_RECOMMENDED_PACKAGES_TRUE@.
+## 'make check-all' is used for running test-Examples-Recommended in
+## addition to 'make check'.
 test-Examples-Recommended: test-Examples-Base
-	@$(MAKE) $(RECOMMENDED_EX_OUT)
-
+	@$(MAKE) $(EX_OUT_RECOMMENDED)
+## </NOTE>
 
 R:
 	@cd $(top_builddir) && $(MAKE) R
 
 .R.Rout:
-	@if test -f $@.bak ; then mv $@.bak $@.bakk ; fi
-	@if test -f $@     ; then cp -p $@  $@.bak  ; fi
+	@if test -f $@; then mv $@ $@.prev; fi
 	@echo $(ECHO_N) "running code in '$<' ...$(ECHO_C)"
-	@$(R) < $< > $@ || (mv $@ $@.fail && exit 1)
+	@$(R) < $< > $@ 2>&1 || (mv $@ $@.fail && exit 1)
 	@echo "$(ECHO_T) OK"
+	@if test -f $@.prev; then \
+	  mv $@ $@.fail; \
+	  echo $(ECHO_N) "comparing '$@' to '$@.prev' ...$(ECHO_C)"; \
+	  $(RDIFF) $@.fail $@.prev $(RVAL_IF_DIFF) || exit 1; \
+	  mv $@.fail $@; \
+	  echo "$(ECHO_T) OK"; \
+	fi
 
-$(EX_IN): FORCE
+## <NOTE>
+## We need to update an ex_in file if it is older than any Rd file it
+## contains examples from, or older than massage-Examples.pl.  As we do
+## not have the Rd files as explicit dependencies (which would currently
+## be impossible for recommended packages), we cannot use Make to figure
+## out the need to update ex_in files ... hence we do things ourselves,
+## and force these computations.
+## The ugly 'find | grep' construct is necessary because 'test -nt' is
+## not portable.  The pipeline will succeed if the target exists and is
+## newer than the corresponding DESCRIPTION file in the package.  If the
+## target does not exist, then find will fail; if it exists and is
+## older, then find will succeed but output nothing so that the grep
+## will fail.
+## </NOTE>
+$(EX_IN_BASE): FORCE
 	@(pkg=`basename $@ -Ex.R`; \
+	if find $@ -newer $(top_srcdir)/share/perl/massage-Examples.pl \
+	    -print 2> /dev/null | grep $@ > /dev/null; then \
+	  target_is_newer_than_massage_Ex=yes; \
+	else \
+	  target_is_newer_than_massage_Ex=no; \
+	fi; \
 	if $(PERL) $(top_srcdir)/tools/Rdnewer.pl \
 	    "$(top_srcdir)/src/library/$${pkg}" "$@"; then \
-	  if test -f $@ ; then \
-	    if test -n "`tail -6 $@ | grep '^Time elapsed'`" ; then \
-	      if test -f $@.bak ; then mv $@.bak $@.bakk ; fi; \
-	      cp -p $@ $@.bak; \
-	    fi; \
-	  fi; \
+	  target_is_newer_than_Rdfiles=no; \
+	else \
+	  target_is_newer_than_Rdfiles=yes; \
+	fi; \
+	if test "$${target_is_newer_than_massage_Ex}" = no \
+	    || test "$${target_is_newer_than_Rdfiles}" = no; then \
 	  echo "collecting examples for package '$${pkg}' ..."; \
 	  (cd $(top_builddir)/src/library && \
 	    OPTS="--txt --example" $(MAKE) R_PKGS_BASE="$${pkg}" DOCS); \
@@ -79,47 +113,42 @@ $(EX_IN): FORCE
 	  touch $@; \
 	fi)
 
-# The ugly "find .. |grep" construct is necessary because "test foo -nt bar" 
-# is nonportable. The pipeline will succeed if the target exists and is newer
-# than the corresponding DESCRIPTION file in the package. If the target does
-# not exist, then find will fail; if it exists and is older, then find will 
-# succeed but output nothing so that the grep will fail.
-$(RECOMMENDED_EX_IN): FORCE
+$(EX_IN_RECOMMENDED): FORCE
 	@(pkg=`basename $@ -Ex.R`; \
-	find $@ -newer $(top_builddir)/library/$${pkg}/DESCRIPTION \
-	 -print 2> /dev/null | grep $@ > /dev/null ||\
-	(\
-	  if test -f $@ ; then \
-	    if test -n "`tail -6 $@ | grep '^Time elapsed'`" ; then \
-	      if test -f $@.bak ; then mv $@.bak $@.bakk ; fi; \
-	      cp -p $@ $@.bak; \
-	    fi; \
-	  fi; \
+	if find $@ -newer $(top_srcdir)/share/perl/massage-Examples.pl \
+	    -print 2> /dev/null | grep $@ > /dev/null; then \
+	  target_is_newer_than_massage_Ex=yes; \
+	else \
+	  target_is_newer_than_massage_Ex=no; \
+	fi; \
+	if find $@ -newer $(top_builddir)/library/$${pkg}/DESCRIPTION \
+	    -print 2> /dev/null | grep $@ > /dev/null; then \
+	  target_is_newer_than_Rdfiles=yes; \
+	else \
+	  target_is_newer_than_Rdfiles=no; \
+	fi; \
+	if test "$${target_is_newer_than_massage_Ex}" = no \
+	    || test "$${target_is_newer_than_Rdfiles}" = no; then \
 	  echo "collecting examples for package '$${pkg}' ..."; \
 	  f=$${TMPDIR-/tmp}/R$$$$; \
 	  $(PERL) $(top_srcdir)/share/perl/massage-Examples.pl $${pkg} \
 	    $(top_builddir)/library/$${pkg}/R-ex > $${f}; \
 	  $(top_srcdir)/tools/move-if-change $${f} $@; \
 	  touch $@; \
-	))
+	fi)
 FORCE:
 
-$(EX_OUT): Makefile \
+$(EX_OUT_BASE) $(EX_OUT_RECOMMENDED): Makefile \
   $(top_builddir)/bin/R.bin \
   $(top_builddir)/library/base/R/base \
   $(top_builddir)/modules/lapack$(SHLIB_EXT)
-$(RECOMMENDED_EX_OUT): Makefile \
-  $(top_builddir)/bin/R.bin \
-  $(top_builddir)/library/base/R/base \
-  $(top_builddir)/modules/lapack$(SHLIB_EXT)
-
 base-Ex.Rout: $(top_builddir)/modules/vfonts$(SHLIB_EXT)
 
 mostlyclean: clean
 clean:
 	-@rm -f *.R *.Rout *.Rd* *.ps *.tex *.dat* data foo* Makedeps
 distclean: clean
-	-@rm -f *.R*bak *.R*bakk .RData sink-examp.txt Makefile
+	-@rm -f *.R*bak *.R*bakk *.R*prev .RData sink-examp.txt Makefile
 maintainer-clean: distclean
 
 distdir: $(DISTFILES)
diff --git a/tests/Makefile.in b/tests/Makefile.in
--- a/tests/Makefile.in
+++ b/tests/Makefile.in
@@ -17,7 +17,6 @@ test-src-gct = \
 	simple-true.R \
 	arith-true.R \
 	arith.R \
-	demos.R \
 	lm-tests.R \
 	primitive-funs.R \
 	ok-errors.R \
@@ -25,83 +24,98 @@ test-src-gct = \
 test-src-strict-1 = \
 	$(test-src-gct) \
 	d-p-q-r-tests.R
-test-src-strict-auto = \
-	isas-tests.R
+test-src-strict-auto =
 test-src-sloppy-1 = \
 	print-tests.R
-test-src-sloppy-auto = \
-	no-segfault.R
+test-src-sloppy-auto =
 
 test-src-1 = $(test-src-strict-1) $(test-src-sloppy-1)
-test-src-auto = $(test-src-strict-auto) $(test-src-sloppy-auto)
+test-src-auto = $(test-src-strict-auto) $(test-src-sloppy-auto) \
+  ${test-src-isas} ${test-src-segfault}
 test-src-sloppy = $(test-src-sloppy-1) $(test-src-sloppy-auto)
 test-src-strict = $(test-src-strict-1) $(test-src-strict-auto)
 test-src = $(test-src-strict) $(test-src-sloppy)
 
+test-src-demo = demos.R demos2.R
 test-src-internet = internet.R
+test-src-isas = isas-tests.R
 test-src-lapack = lapack.R
 test-src-nafns = nafns.R
 test-src-random = p-r-random-tests.R
 test-src-postscript = ps-tests.R
 test-src-ts = ts-tests.R
+test-src-segfault = no-segfault.R
 
-test-src-reg-1 = \
-	reg-tests-1.R reg-tests-2.R reg-IO.R reg-IO2.R reg-plot.R
+test-src-reg-1 = reg-tests-1.R reg-tests-2.R reg-IO.R reg-IO2.R reg-plot.R
 test-src-reg-auto =
 test-src-reg = $(test-src-reg-1) $(test-src-reg-auto)
 
-all-basic-tests = Examples Specific
-all-extra-tests = Internet Lapack Nafns Postscript Random Reg \
-  DocArgs FF Methods codoc undoc
 
 DISTFILES = Makefile.in Makefile.win README \
 	$(test-src-strict-1) $(test-src-strict-1:.R=.Rout.save) \
 	$(test-src-sloppy-1) $(test-src-sloppy-1:.R=.Rout.save) \
 	$(test-src-auto:.R=.Rin) isas-tests.Rout.save \
+	$(test-src-demo) demos.Rout.save \
 	$(test-src-internet) internet.Rout.save \
 	$(test-src-lapack) \
 	$(test-src-nafns) \
 	$(test-src-postscript) ps-tests.Rout.save \
 	$(test-src-random) p-r-random-tests.Rout.save \
 	$(test-src-reg) reg-IO.Rout.save reg-IO2.Rout.save \
-	  reg-plot.Rout.save reg-tests-2.Rout.save \
+	  reg-plot.Rout.save reg-plot.ps.save reg-tests-2.Rout.save \
 	$(test-src-ts) \
 	gct-foot.R \
 	nanbug.rda
 SUBDIRS = Embedding Examples Native
 
 R = LC_ALL=C SRCDIR=$(srcdir) $(top_builddir)/bin/R --vanilla
-RDIFF = $(top_builddir)/bin/Rdiff
+RDIFF = $(top_builddir)/bin/R CMD Rdiff
 
 test-out-strict = $(test-src-strict:.R=.Rout)
 test-out-sloppy = $(test-src-sloppy:.R=.Rout)
 
 test-out-gct = $(test-src-gct:.R=.Rout-gct)
 
+test-out-demo = $(test-src-demo:.R=.Rout)
 test-out-internet = $(test-src-internet:.R=.Rout)
+test-out-isas = $(test-src-isas:.R=.Rout)
 test-out-lapack = $(test-src-lapack:.R=.Rout)
 test-out-nafns = $(test-src-nafns:.R=.Rout)
 test-out-postscript = $(test-src-postscript:.R=.Rout)
 test-out-random = $(test-src-random:.R=.Rout)
 test-out-reg = $(test-src-reg:.R=.Rout)
+test-out-segfault = $(test-src-segfault:.R=.Rout)
 test-out-ts = $(test-src-ts:.R=.Rout)
 
-test-out = $(test-src:.R=.Rout) $(test-out-gct) \
+## This macro is used only for dependencies
+test-out = $(test-src:.R=.Rout) $(test-out-demo) $(test-out-gct) \
 	$(test-out-internet) $(test-out-lapack) $(test-out-nafns) \
 	$(test-out-random) $(test-out-postscript) $(test-out-reg) \
-	$(test-out-ts)
+	$(test-out-segfault) $(test-out-ts) $(test-out-isas)
 
 .SUFFIXES:
 .SUFFIXES: .R .Rin .Rout .Rout-gct
 
+all-basic-tests = Examples Specific Reg Internet
+all-devel-tests = IsAs Lapack Nafns Postscript Random Demo Segfault \
+   Standalone Packages
+
 all check: Makefile test-all-basics
-fullcheck: check test-Examples-Recommended
+check-devel: check test-all-devel
+check-all: check-devel test-Examples-Recommended
 
 Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
 	@cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@
 
+$(test-out): Makefile stamp-R
+
+stamp-R: $(top_builddir)/bin/R.bin $(top_builddir)/library/base/R/base \
+	$(top_builddir)/library/methods/R/all.rda \
+	$(top_builddir)/library/methods/R/methods
+	@touch $@
+
 Makedeps: Makefile
-	@(for f in $(test-src) $(test-src-reg); do \
+	@(for f in $(test-src) $(test-src-reg) $(test-src-demo); do \
 	    if test -f $(srcdir)/$${f}out.save ; then \
 	      echo "$${f}out: $${f} \$$(srcdir)/$${f}out.save \$$(FORCE)"; \
 	    else \
@@ -121,7 +135,7 @@ FORCE:
 .R.Rout:
 	@rm -f $@ $@.fail
 	@echo $(ECHO_N) "running code in '$<' ...$(ECHO_C)"
-	@$(R) < $< > $@ || (mv $@ $@.fail && exit 1)
+	@$(R) < $< > $@ 2>&1 || (mv $@ $@.fail && exit 1)
 	@echo "$(ECHO_T) OK"
 	@if test -f $(srcdir)/$@.save ; then \
 	  mv $@ $@.fail; \
@@ -132,14 +146,32 @@ FORCE:
 	  echo "$(ECHO_T) OK"; \
 	fi
 
+reg-plot.Rout: reg-plot.R
+	@rm -f $@ $@.fail
+	@echo $(ECHO_N) "running code in '$<' ...$(ECHO_C)"
+	@$(R) < $< > $@ 2>&1 || (mv $@ $@.fail && exit 1)
+	@echo "$(ECHO_T) OK"
+	@if test -f $(srcdir)/$@.save ; then \
+	  mv $@ $@.fail; \
+	  echo $(ECHO_N) \
+	    "comparing '$@' to '$(srcdir)/$@.save' ...$(ECHO_C)"; \
+	  $(RDIFF) $@.fail $(srcdir)/$@.save $(RVAL_IF_DIFF) || exit 1; \
+	  mv $@.fail $@; \
+	  echo "$(ECHO_T) OK"; \
+	fi
+	@echo $(ECHO_N) \
+	  "comparing 'reg-plot.ps' to '$(srcdir)/reg-plot.ps.save' ...$(ECHO_C)"
+	@$(RDIFF) reg-plot.ps $(srcdir)/reg-plot.ps.save $(RVAL_IF_DIFF)
+	@echo "$(ECHO_T) OK"
+
 .R.Rout-gct:
 	@echo "running gctorture() + '$<'"
 	@(echo '.ptime <- proc.time(); gctorture()' ; \
-	  cat $< $(srcdir)/gct-foot.R) | $(R) > $@
+	  cat $< $(srcdir)/gct-foot.R) | $(R) > $@ 2>&1
 	@mv $@ $@.fail; Ro=`basename $@ .Rout-gct`.Rout; \
-	  if test ! -r $$Ro ; then $(MAKE) $$Ro ; fi; \
-	  echo $(ECHO_N) "comparing '$@' to '$$Ro' ...$(ECHO_C)"; \
-	  grep -v 'gctorture()' $@.fail | $(RDIFF) - $$Ro  1 || exit 1; \
+	  if test ! -r $${Ro}; then $(MAKE) $${Ro}; fi; \
+	  echo $(ECHO_N) "comparing '$@' to '$${Ro}' ...$(ECHO_C)"; \
+	  grep -v 'gctorture()' $@.fail | $(RDIFF) - $${Ro} 1 || exit 1; \
 	  mv $@.fail $@; \
 	  echo "$(ECHO_T) OK"
 
@@ -147,10 +179,17 @@ test-all-basics: Makefile
 	@for name in $(all-basic-tests); do \
 	  $(MAKE) test-$${name} || exit 1; \
 	done
+
+test-all-devel: Makefile
+	@for name in $(all-devel-tests); do \
+	  $(MAKE) test-$${name} || exit 1; \
+	done
+
 test-Examples:
 	@(cd Examples && $(MAKE) $@)
 test-Examples-Recommended:
 	@(cd Examples && $(MAKE) $@)
+
 test-Specific-strict: $(test-out-strict)
 test-Specific-sloppy: $(test-out-sloppy)
 test-Specific:
@@ -160,7 +199,6 @@ test-Specific:
 	@$(MAKE) test-Specific-strict RVAL_IF_DIFF=1
 	@echo "running sloppy specific tests"
 	@$(MAKE) test-Specific-sloppy RVAL_IF_DIFF=0
-	@rm -f data F.Rd c0.Rd df0.Rd l0.Rd
 
 test-Packages:
 	@for p in $(R_PKGS_BASE); do \
@@ -171,31 +209,60 @@ test-Packages:
 
 test-Gct: $(test-out-gct)
 
-test-all-extras: Makefile
-	@for name in $(all-extra-tests); do \
-	  $(MAKE) test-$${name} || exit 1; \
-	done
+test-Demo:
+	@echo "running demos from base and eda"
+	@$(MAKE) $(test-out-demo) RVAL_IF_DIFF=0
+
+## <NOTE>
+## These depend on an internet connection, and the sites being up.
+## So allow this to fail: it may be slow doing so.
 test-Internet:
 	@echo "running tests of Internet and socket functions"
-	@$(MAKE) $(test-out-internet) RVAL_IF_DIFF=0
+	@echo "  expect some differences"
+	-@$(MAKE) $(test-out-internet) RVAL_IF_DIFF=0
+## </NOTE>
+
+test-IsAs:
+	@echo "running tests of consistency of as/is.*"
+	@$(MAKE) $(test-out-isas) RVAL_IF_DIFF=1
+
 test-Lapack:
 	@echo "running tests of LAPACK-based functions"
 	@$(MAKE) $(test-out-lapack) RVAL_IF_DIFF=0
+
 test-Nafns:
 	@echo "running tests of NA handling functions"
 	@$(MAKE) $(test-out-nafns) RVAL_IF_DIFF=0
+
 test-Postscript:
 	@echo "running tests of postscript() families"
 	@$(MAKE) $(test-out-postscript) RVAL_IF_DIFF=0
+
 test-Random:
 	@echo "running tests of random deviate generation"
 	@$(MAKE) $(test-out-random) RVAL_IF_DIFF=1
+
 test-Reg:
 	@echo "running regression tests"
 	@$(MAKE) $(test-out-reg) RVAL_IF_DIFF=0
+
+test-Segfault:
+	@echo "running tests to possibly trigger segfaults"
+	@$(MAKE) $(test-out-segfault) RVAL_IF_DIFF=0
+	@rm -f data dumpdata.R F.Rd c0.Rd df0.Rd l0.Rd m0.Rd Rprof.out Rplots.*
+
+## <NOTE>
+## Not all platforms can build standalone.
+## So allow this to fail.
+test-Standalone:
+	@echo "testing building standalone Rmath"
+	-@(cd $(top_builddir)/src/nmath/standalone; $(MAKE) check)
+## </NOTE>
+
 test-Ts:
 	@echo "running tests of package ts functions"
 	@$(MAKE) $(test-out-ts) RVAL_IF_DIFF=0
+
 test-DocArgs:
 	@echo "checking whether arguments from usage are documented"
 	@for p in $(R_PKGS_BASE); do \
@@ -295,17 +362,13 @@ test-undoc:
 	  fi; \
 	done
 
-$(test-out): Makefile stamp-R
-stamp-R: $(top_builddir)/bin/R.bin $(top_builddir)/library/base/R/base
-	@touch $@
-
 mostlyclean: clean
 clean:
 	-@for d in $(SUBDIRS); do \
 	  (cd $${d} && $(MAKE) $@); \
 	done
 	-@rm -f stamp-R Makedeps Rplot* Rprof.out *.Rd data dumpdata.R \
-	  reg-plot.ps
+	  reg-plot.ps reg-tests-2.ps
 	-@rm -rf anRpackage
 distclean: clean
 	-@for d in $(SUBDIRS); do \
