adding v2.0.0

diff --git a/doc/manual/Makefile.in b/doc/manual/Makefile.in
--- a/doc/manual/Makefile.in
+++ b/doc/manual/Makefile.in
@@ -49,7 +49,7 @@ R_RD4PDF = @R_RD4PDF@
 
 texinputs_BASE = $(R_PKGS_BASE:=-pkg.tex)
 texinputs_RECOMMENDED = $(R_PKGS_RECOMMENDED:=-pkg.tex)
-R_PKGS_refman = base graphics grid methods stats tools utils
+R_PKGS_refman = base datasets grDevices graphics grid methods stats tools utils
 refman_TEXINPUTS = $(R_PKGS_refman:=-pkg.tex)
 refman_DEPENDENCIES = version.tex $(top_srcdir)/share/texmf/Rd.sty
 fullrefman_TEXINPUTS = $(texinputs_BASE) @USE_RECOMMENDED_PACKAGES_TRUE@ $(texinputs_RECOMMENDED)
@@ -74,20 +74,34 @@ docs: html
 	  exit 1; \
 	fi
 	TEXINPUTS="$(srcdir):$$TEXINPUTS" $(TEXI2DVI) $<
+
 .texi.html:
 	$(TEXI2HTML) -D UseExternalXrefs -I$(srcdir) $< -o $@ || touch $@
+
 .texi.info:
 	@if test "$(MAKEINFO)" = false; then \
-	  echo "ERROR: 'makeinfo' v4 needed but missing on your system."; \
+	  echo "ERROR: 'makeinfo' v4.5 or later needed but missing on your system."; \
 	  exit 1; \
 	fi
 	$(MAKEINFO) -D UseExternalXrefs -I$(srcdir) $<
+
 .texi.pdf:
 	@if test "$(PDFTEX)" = false; then \
 	  echo "ERROR: 'pdftex' needed but missing on your system."; \
 	  exit 1; \
 	fi
 	TEXINPUTS="$(srcdir):$$TEXINPUTS" $(TEXI2PDF) $<
+
+## we have to be careful not to install a local R-admin.html made prior to
+## texinfo 4.7, as doc/html/SearchEngine.html links to it.
+## So use that in the sources if we can -- it is not in the svn archive.
+## There are no cross-references, external or not.
+R-admin.html:
+	if test -f "$(top_srcdir)/doc/html/R-admin.html" ; then \
+	  cp "$(top_srcdir)/doc/html/R-admin.html" R-admin.html ; \
+	else \
+	  $(TEXI2HTML) -I$(srcdir) $(srcdir)/R-admin.texi -o $@ || touch $@ ; \
+	fi
 
 dvi: refman.dvi $(OBJECTS_DVI)
 refman.dvi: $(refman_DEPENDENCIES) stamp-refman-dvi
@@ -100,9 +114,9 @@ refman.dvi: $(refman_DEPENDENCIES) stamp-refman-dvi
 ## <NOTE>
 ## We do not make sure echo does not interpret backslash escapes.
 ## Could be trouble ...
-	@(opt="$${R_PAPERSIZE-$(R_PAPERSIZE)}paper"; \
+	@(opt="$(R_PAPERSIZE)paper"; \
 	  echo "\\documentclass[$${opt}]{book}"; \
-	  opt="$${R_RD4DVI-$(R_RD4DVI)}"; \
+	  opt="$(R_RD4DVI)"; \
 	  echo "\\usepackage[$${opt}]{Rd}"; \
 	  cat $(srcdir)/refman.top; \
 	  texinputs=`(for f in $(refman_TEXINPUTS); \
@@ -116,11 +130,13 @@ refman.dvi: $(refman_DEPENDENCIES) stamp-refman-dvi
 	@TEXINPUTS="$(top_srcdir)/share/texmf:$$TEXINPUTS" \
 	  $(LATEX) '\nonstopmode\input{refman.tex}'
 	@touch stamp-refman-dvi
+
 version.tex: Makefile $(top_srcdir)/date-stamp $(top_srcdir)/VERSION
 	@echo "creating $(subdir)/$@"
 	@(v=`cat $(top_srcdir)/VERSION`; \
 	  v="$${v} (`sed 's|/|-|g' $(top_srcdir)/date-stamp`)"; \
 	  echo "$${v}") > $@
+
 stamp-refman-dvi: $(refman_TEXINPUTS)
 	@touch $@
 
@@ -152,9 +168,9 @@ fullrefman.dvi: $(refman_DEPENDENCIES) stamp-fullrefman-dvi
 	fi
 	@echo "DVI/LaTeX documentation: full reference index ..."
 	@rm -f *.aux fullrefman.toc fullrefman.ind stamp-fullrefman-dvi
-	@(opt="$${R_PAPERSIZE-$(R_PAPERSIZE)}paper"; \
+	@(opt="$(R_PAPERSIZE)paper"; \
 	  echo "\\documentclass[$${opt}]{book}"; \
-	  opt="$${R_RD4DVI-$(R_RD4DVI)}"; \
+	  opt="$(R_RD4DVI)"; \
 	  echo "\\usepackage[$${opt}]{Rd}"; \
 	  cat $(srcdir)/refman.top; \
 	  echo "\\part{}"; \
@@ -189,6 +205,10 @@ version.texi: Makefile $(top_srcdir)/VERSION $(top_srcdir)/date-stamp
 	  echo "@set VERSION $${v}" >> $@; \
 	  rwv=`$(PERL) $(top_srcdir)/src/gnuwin32/fixed/rwver.pl $(top_srcdir)/VERSION`; \
 	  echo "@set RWVERSION $${rwv}" >> $@ )
+	if test "$(R_PAPERSIZE)" = "a4"; then \
+	  echo "@afourpaper" >> $@ ; \
+	fi
+
 R-intro.dvi: stamp-images-eps $(texiincludes)
 stamp-images-eps:
 	@if test "$(BUILDDIR_IS_SRCDIR)" = no ; then \
@@ -224,9 +244,9 @@ refman.pdf: $(refman_DEPENDENCIES) stamp-refman-pdf
 ## <NOTE>
 ## We do not make sure echo does not interpret backslash escapes.
 ## Could be trouble ...
-	@(opt="$${R_PAPERSIZE-$(R_PAPERSIZE)}paper"; \
+	@(opt="$(R_PAPERSIZE)paper"; \
 	  echo "\\documentclass[$${opt}]{book}"; \
-	  opt="$${R_RD4PDF-$(R_RD4PDF)}"; \
+	  opt="$(R_RD4PDF)"; \
 	  echo "\\usepackage[$${opt}]{Rd}"; \
 	  cat $(srcdir)/refman.top; \
 	  texinputs=`(for f in $(refman_TEXINPUTS); \
@@ -254,9 +274,9 @@ fullrefman.pdf: $(refman_DEPENDENCIES) stamp-fullrefman-pdf
 	fi
 	@echo "PDF/LaTeX documentation: full reference index ..."
 	@rm -f *.aux fullrefman.toc fullrefman.ind stamp-fullrefman-pdf
-	@(opt="$${R_PAPERSIZE-$(R_PAPERSIZE)}paper"; \
+	@(opt="$(R_PAPERSIZE)paper"; \
 	  echo "\\documentclass[$${opt}]{book}"; \
-	  opt="$${R_RD4PDF-$(R_RD4PDF)}"; \
+	  opt="$(R_RD4PDF)"; \
 	  echo "\\usepackage[$${opt}]{Rd}"; \
 	  cat $(srcdir)/refman.top; \
 	  echo "\\part{}"; \
@@ -300,31 +320,32 @@ install: install-message installdirs install-html
 install-message:
 	@echo "installing $(subdir) ..."
 installdirs:
-	@$(MKINSTALLDIRS) $(rhome)/$(subdir)
+	@$(MKINSTALLDIRS) "$(rhome)/$(subdir)"
 install-strip: install
 install-dvi: dvi installdirs install-images-eps
 	@echo "installing R manuals in DVI format ..."
 	@for f in *.dvi; do \
-	  $(INSTALL_DATA) $${f} $(rhome)/$(subdir); \
+	  $(INSTALL_DATA) $${f} "$(rhome)/$(subdir)"; \
 	done
 install-images-eps:
-	@$(MKINSTALLDIRS) $(rhome)/$(subdir)/images
+	@$(MKINSTALLDIRS) "$(rhome)/$(subdir)"/images
 	@-for f in $(srcdir)/images/*.eps; do \
-	  $(INSTALL_DATA) $${f} $(rhome)/$(subdir)/images; \
+	  $(INSTALL_DATA) $${f} "$(rhome)/$(subdir)"/images; \
 	done
 install-images-pdf:
-	@$(MKINSTALLDIRS) $(rhome)/$(subdir)/images
+	@$(MKINSTALLDIRS) "$(rhome)/$(subdir)"/images
 	@-for f in $(srcdir)/images/*.pdf; do \
-	  $(INSTALL_DATA) $${f} $(rhome)/$(subdir)/images; \
+	  $(INSTALL_DATA) $${f} "$(rhome)/$(subdir)"/images; \
 	done
 install-html:
 	@for f in $(OBJECTS_HTML); do \
-	  $(INSTALL_DATA) $${f} $(rhome)/$(subdir); \
+	  $(INSTALL_DATA) $${f} "$(rhome)/$(subdir)"; \
 	done
 install-info: info $(infodir)/dir
 	@echo "installing R info pages ..."
 	@for f in $(OBJECTS_INFO:.info=.info*); do \
-	  $(INSTALL_DATA) $${f} $(infodir); \
+	  $(INSTALL_DATA) $${f} "$(infodir)"; \
+	  $(R_GZIPCMD) -f "$(infodir)/$${f}"; \
 	done
 	@echo "updating '$(infodir)/dir' ..."
 	@for f in $(OBJECTS_INFO); do \
@@ -334,24 +355,25 @@ install-info: info $(infodir)/dir
 install-pdf: pdf installdirs
 	@echo "installing R manuals in PDF format ..."
 	@for f in *.pdf; do \
-	  $(INSTALL_DATA) $${f} $(rhome)/$(subdir); \
+	  $(INSTALL_DATA) $${f} "$(rhome)/$(subdir)"; \
 	done
 
 $(infodir)/dir:
-	@$(MKINSTALLDIRS) $(infodir)
-	$(INSTALL_DATA) $(srcdir)/dir $(infodir)
+	@$(MKINSTALLDIRS) "$(infodir)"
+	$(INSTALL_DATA) "$(srcdir)/dir" "$(infodir)"
 
 uninstall:
-	@if test -f $(infodir)/R-data.info; then \
+	@if test -f "$(infodir)/R-data.info" \
+	     || test -f "$(infodir)/R-data.info.gz"; then \
 	  $(MAKE) uninstall-info; \
 	fi
 	@echo "uninstalling $(subdir) ..."
-	@rm -rf $(rhome)/$(subdir)
+	@rm -rf "$(rhome)/$(subdir)"
 uninstall-dvi:
 	@echo "uninstalling R manuals in DVI format ..."
-	@-rm -f $(rhome)/$(subdir)/images/*.eps
-	@-rmdir $(rhome)/$(subdir)/images
-	@-rm -f $(rhome)/$(subdir)/*.dvi
+	@-rm -f "$(rhome)/$(subdir)"/images/*.eps
+	@-rmdir "$(rhome)/$(subdir)"/images
+	@-rm -f "$(rhome)/$(subdir)"/*.dvi
 uninstall-info:
 	@echo "uninstalling R info pages ..."
 	@for f in $(OBJECTS_INFO); do \
@@ -359,11 +381,11 @@ uninstall-info:
 	    || echo "you need to adjust $(infodir)/dir manually"; \
 	done
 	@for f in $(OBJECTS_INFO:.info=.info*); do \
-	  rm -f $(infodir)/$${f}; \
+	  rm -f "$(infodir)/$${f}" "$(infodir)/$${f}.gz" ; \
 	done
 uninstall-pdf:
 	@echo "uninstalling R manuals in PDF format ..."
-	@-rm -f $(rhome)/$(subdir)/*.pdf
+	@-rm -f "$(rhome)/$(subdir)"/*.pdf
 
 mostlyclean: clean
 clean:
@@ -384,8 +406,7 @@ maintainer-build: \
   $(top_srcdir)/FAQ \
   $(top_srcdir)/RESOURCES \
   $(top_srcdir)/doc/html/faq.html \
-  $(top_srcdir)/doc/html/resources.html \
-  $(top_srcdir)/doc/html/R-admin.html
+  $(top_srcdir)/doc/html/resources.html
 $(top_srcdir)/FAQ: @MAINTAINER_MODE_TRUE@ $(srcdir)/R-FAQ.texi
 	@if test "$(MAKEINFO)" = false; then \
 	  echo "ERROR: 'makeinfo' v4 needed but missing on your system."; \
@@ -410,13 +431,6 @@ $(top_srcdir)/doc/html/resources.html: @MAINTAINER_MODE_TRUE@ $(srcdir)/resource
 	  exit 1; \
 	fi
 	$(TEXI2HTML) --no-headers $(srcdir)/resources.texi -o $@
-$(top_srcdir)/doc/html/R-admin.html: @MAINTAINER_MODE_TRUE@ $(srcdir)/R-admin.texi $(texiincludes)
-	@if test "$(MAKEINFO)" = false; then \
-	  echo "ERROR: 'makeinfo' v4 needed but missing on your system."; \
-	  exit 1; \
-	fi
-	$(TEXI2HTML) --no-headers --number-sections -I$(srcdir) \
-	  $(srcdir)/R-admin.texi -o $@
 
 distdir: $(DISTFILES)
 	@for f in $(DISTFILES); do \
@@ -425,7 +439,15 @@ distdir: $(DISTFILES)
 	    || cp -p $(srcdir)/$${f} $(distdir)/$${f}; \
 	done
 	@for d in $(SUBDIRS_WITH_NO_BUILD); do \
-	  ((cd $(srcdir); $(TAR) -c -f - --exclude=CVS $${d}) \
+	  ((cd $(srcdir); $(TAR) -c -f - $(DISTDIR_TAR_EXCLUDE) $${d}) \
 	      | (cd $(distdir); $(TAR) -x -f -)) \
 	    || exit 1; \
 	done
+	@if test "$(MAKEINFO)" = false; then \
+	  echo "ERROR: 'makeinfo' v4 needed but missing on your system."; \
+	  exit 1; \
+	fi
+#	$(distdir)/doc/html has already been created
+	$(TEXI2HTML) --no-headers --number-sections \
+	  $(srcdir)/R-admin.texi -I$(srcdir) \
+	  -o $(distdir)/../html/R-admin.html
diff --git a/src/gnuwin32/MakePkg b/src/gnuwin32/MakePkg
--- a/src/gnuwin32/MakePkg
+++ b/src/gnuwin32/MakePkg
@@ -3,15 +3,19 @@ RLIB=../../../library
 DPKG=$(RLIB)/$(PKG)
 SPKG=.
 SAVE=CHECK
+LAZY=false
+LAZYDATA=false
 
 ifneq ($(strip $(BUILD)),CROSS)
 SPKG0 = $(shell $(RHOME)/src/gnuwin32/Rpwd.exe $(SPKG))
 DPKG0 = $(shell $(RHOME)/src/gnuwin32/Rpwd.exe $(DPKG))
+R_EXE = $(RHOME)/bin/rterm.exe
 else
 SPKG0=$(SPKG)
 DPKG0=$(DPKG)
 endif
 
+REXE = $(R_EXE) --vanilla --slave
 
 ifeq ($(strip $(DLLNM)),)
   DLLNAME=$(PKG)
@@ -37,7 +41,7 @@ else
 endif
 
 # data
-DSOURCES=$(filter-out $(SPKG)/data/CVS $(SPKG)/data/.svn, $(wildcard $(SPKG)/data/*))
+DSOURCES=$(filter-out $(SPKG)/data/CVS $(SPKG)/data/.svn $(SPKG)/data/datalist, $(wildcard $(SPKG)/data/*))
 ifeq ($(strip $(DSOURCES)),)
   DATA= 
 else
@@ -56,7 +60,7 @@ endif
 
 # demos
 PKGDEMOS0=$(wildcard $(SPKG)/demo/*)
-PKGDEMOS=$(filter-out $(SPKG)/demo/CVS $(SPKG)/demo/.svn, $(PKGDEMOS0))
+PKGDEMOS=$(filter-out $(SPKG)/demo/CVS $(SPKG)/demo/.svn $(SPKG)/demo/00Index, $(PKGDEMOS0))
 
 # exec
 EXECFILES=$(filter-out $(SPKG)/exec/CVS $(SPKG)/exec/.svn, $(wildcard $(SPKG)/exec/*))
@@ -70,7 +74,13 @@ all:
 	@$(MAKE) --no-print-directory -f $(RHOME)/src/gnuwin32/MakePkg -s nmspace
 	@$(MAKE) --no-print-directory -f $(RHOME)/src/gnuwin32/MakePkg Dynlib 
 	@$(MAKE) --no-print-directory -f $(RHOME)/src/gnuwin32/MakePkg -s R
+ifeq ($(strip $(LAZY)),true)
+	@$(MAKE) --no-print-directory -f $(RHOME)/src/gnuwin32/MakePkg -s lazyload
+endif
 	@$(MAKE) --no-print-directory -f $(RHOME)/src/gnuwin32/MakePkg -s $(DPKG)/demo $(DPKG)/exec $(DPKG)/inst $(DATA)
+ifeq ($(strip $(LAZYDATA)),true)
+	@$(MAKE) --no-print-directory -f $(RHOME)/src/gnuwin32/MakePkg -s lazydata
+endif
 	@$(MAKE) --no-print-directory -f $(RHOME)/src/gnuwin32/MakePkg -s mansrcs indices
 
 fake: zzzfirst frontmatter nmspacefake R Rfake $(DPKG)/demo \
@@ -80,7 +90,9 @@ include $(RHOME)/src/gnuwin32/MkRules
 
 clean:
 ifeq ($(strip $(SRCMAKE)),)
-	$(RM) $(SDYNLIB) $(LOBJS) $(SSPKG)/$(DLLNAME).a  $(SSPKG)/$(DLLNAME).def $(SSPKG)/$(DLLNAME)_res.* $(SSPKG)/*.d $(SSPKG)/Makedeps
+	$(RM) $(SDYNLIB) $(LOBJS) $(SSPKG)/$(DLLNAME).a \
+	  $(SSPKG)/$(DLLNAME).def $(SSPKG)/$(DLLNAME)_res.* \
+	  $(SSPKG)/*.d $(SSPKG)/Makedeps
 else
 	$(MAKE) -C $(SSPKG) RHOME=$(RHOME) -f Makefile.win clean
 endif
@@ -93,6 +105,8 @@ Rcode: Rcode0 Dynlib
 Rcode0:
 	@$(MKDIR) -p $(DPKG) $(DPKG)/R
 	@$(CAT) $(PKGRFILES) > $(DPKG)/R/$(PKG)
+#	@cp -p $(DPKG)/R/$(PKG) $(DPKG)/R/all.R
+	@rm -f $(DPKG)/R/$(PKG).rdb  $(DPKG)/R/$(PKG).rdx
 	@if test -f ${SPKG}/NAMESPACE; then \
 	  $(CP) ${SPKG}/NAMESPACE $(DPKG)/NAMESPACE; \
 	fi
@@ -104,24 +118,20 @@ ifneq ($(strip $(PKG)),base)
 ifneq ($(strip $(PKGRFILES)),)
 	@$(ECHO) "  installing R files"
 	@$(MKDIR) -p $(DPKG)/R
-ifeq ($(strip $(BUILD)),CROSS)
-	@$(ECHO) ".installPackageCodeFiles('"$(SPKG)"', '"$(DPKG)"')" \
-	  | R_DEFAULT_PACKAGES=tools R_OSTYPE=windows LC_COLLATE=C $(R_EXE) --vanilla --slave > /dev/null
-else
-	@$(ECHO) ".installPackageCodeFiles('"$(SPKG)"', '"$(DPKG)"')" \
-	  | $(RHOME)/bin/rterm.exe --vanilla --slave \
-	    R_DEFAULT_PACKAGES=tools LC_COLLATE=C > /dev/null
-endif
+	@$(ECHO) "tools:::.install_package_code_files('"$(SPKG)"', '"$(DPKG)"')" \
+	  | R_DEFAULT_PACKAGES=NULL R_OSTYPE=windows LC_COLLATE=C $(REXE) > /dev/null
 ## install halts here if collater failed
-	@sh $(RHOME)/src/gnuwin32/install-save.sh $(SAVE) $(RLIB) $(PKG) $(RHOME) $(BUILD) $(R_EXE)
+	@rm -f $(DPKG)/R/$(PKG).rdb $(DPKG)/R/$(PKG).rdx $(DPKG)/R/all.rda
+	@sh $(RHOME)/src/gnuwin32/install-save.sh "$(SAVE)" $(RLIB) $(PKG) $(RHOME) $(BUILD) $(R_EXE)
 else
 	@$(ECHO) "  no R files in this package"
 endif
 else
-## .installPackageCodeFiles adds an unwanted .packageName
+## .install_package_code_files adds an unwanted .packageName
 	@$(ECHO) "  installing R files"
 	@$(MKDIR) -p $(DPKG)/R
 	@$(CAT) $(PKGRFILES) > $(DPKG)/R/$(PKG)
+	@rm -f $(DPKG)/R/$(PKG).rdb $(DPKG)/R/$(PKG).rdx
 endif
 
 $(DPKG)/demo: $(PKGDEMOS)
@@ -182,40 +192,21 @@ frontmatter:
 	  $(ECHO) "A package must contain a DESCRIPTION file"; \
 	  exit 27; \
 	fi
-ifeq ($(strip $(BUILD)),CROSS)
-	@$(ECHO) ".installPackageDescription('.', '"$(DPKG)"')" | \
-	  R_DEFAULT_PACKAGES=tools R_OSTYPE=windows $(R_EXE) --vanilla --slave > /dev/null
-else
-	@$(ECHO) ".installPackageDescription('.', '"$(DPKG)"')" | \
-	  $(RHOME)/bin/rterm.exe --vanilla --slave R_DEFAULT_PACKAGES=tools > /dev/null
-endif
+	@$(ECHO) "tools:::.install_package_description('.', '"$(DPKG)"')" | \
+	  R_DEFAULT_PACKAGES=NULL R_OSTYPE=windows $(REXE) > /dev/null
+	@if test -f ${SPKG}/COPYING; then \
+	  $(CP) ${SPKG}/COPYING $(DPKG)/COPYING; \
+	fi
 
 nmspace:
-ifeq ($(strip $(BUILD)),CROSS)
 	@if test -f ${SPKG}/NAMESPACE; then \
 	  $(ECHO) -n "  installing NAMESPACE file"; \
-	  if test -f ${SPKG}/NAMESPACE.windows ; then \
-	  cat ${SPKG}/NAMESPACE ${SPKG}/NAMESPACE.windows > $(DPKG)/NAMESPACE; \
-	  else \
-	    $(CP) ${SPKG}/NAMESPACE $(DPKG)/NAMESPACE; \
-          fi ; \
+	  $(CP) ${SPKG}/NAMESPACE $(DPKG)/NAMESPACE; \
 	  $(ECHO) " and metadata"; \
-	  $(ECHO) ".installPackageNamespaceInfo('$(DPKG)', '$(DPKG)')" | \
-	    R_DEFAULT_PACKAGES=tools R_OSTYPE=windows $(R_EXE) --vanilla --slave > /dev/null; \
+	  $(ECHO) "tools:::.install_package_namespace_info('$(DPKG)', '$(DPKG)')" | \
+	  R_DEFAULT_PACKAGES=NULL R_OSTYPE=windows $(REXE) > /dev/null; \
 	fi
-else
-	@if test -f ${SPKG}/NAMESPACE; then \
-	  $(ECHO) -n "  installing NAMESPACE file"; \
-	  if test -f ${SPKG}/NAMESPACE.windows ; then \
-	  cat ${SPKG}/NAMESPACE ${SPKG}/NAMESPACE.windows > $(DPKG)/NAMESPACE; \
-	  else \
-	    $(CP) ${SPKG}/NAMESPACE $(DPKG)/NAMESPACE; \
-          fi ; \
-	  $(ECHO) " and metadata"; \
-	  $(ECHO) ".installPackageNamespaceInfo('$(DPKG)', '$(DPKG)')" | \
-	    $(RHOME)/bin/rterm.exe R_DEFAULT_PACKAGES=tools --vanilla --slave > /dev/null; \
-	fi
-endif
+
 nmspacefake:
 	@if test -f ${SPKG}/NAMESPACE; then \
 	  $(ECHO) "  installing NAMESPACE file"; \
@@ -247,14 +238,15 @@ ifneq ($(strip $(LOBJS)),)
 endif
 else
 	@$(ECHO) "  running src/Makefile.win ..."
-	@$(MAKE) --no-print-directory -C $(SSPKG) RHOME=$(RHOME) -f Makefile.win
+	@$(MAKE) --no-print-directory -C $(SSPKG) RHOME=$(RHOME) \
+	  -f Makefile.win
 	@$(ECHO) "  ... done"
 endif
 
 # R
 AA=$(wildcard R/Makefile.win)
 ifeq ($(AA),)
- R: $(DPKG)/R/$(PKG)
+ R: $(DPKG)/R/$(PKG) sysdata
 else
  include R/Makefile.win
 endif
@@ -270,28 +262,24 @@ Rfake:
 MANMAIN=$(wildcard $(SPKG)/man/*.[Rr]d)
 MANWIN32=$(wildcard $(SPKG)/man/windows/*.[Rr]d) 
 
-mansrcs: $(DPKG)/man/$(PKG).Rd
+mansrcs: $(DPKG)/man/$(PKG).Rd.gz
 
 PKGMANFILES=$(MANMAIN) $(MANWIN32)
-$(DPKG)/man/$(PKG).Rd: $(MANMAIN) $(MANWIN32)
+$(DPKG)/man/$(PKG).Rd.gz: $(MANMAIN) $(MANWIN32)
 ifneq ($(strip $(PKGMANFILES)),)
 	@$(ECHO) "  installing man source files"
 	@$(RM) -rf $(DPKG)/man
 	@$(MKDIR) -p $(DPKG)/man
 	sh $(RHOME)/src/gnuwin32/man-install.sh $(DPKG)/man/$(PKG).Rd '$^'
+	@gzip -9 $(DPKG)/man/$(PKG).Rd
 else
 	@$(ECHO) "  no man files in this package"
 endif
 
 indices:
 	@$(ECHO) "  installing indices"
-ifeq ($(strip $(BUILD)),CROSS)
-	@$(ECHO) ".installPackageIndices('.', '"$(DPKG)"')" | \
-	  R_DEFAULT_PACKAGES=tools LC_COLLATE=C R_OSTYPE=windows $(R_EXE) --vanilla --slave > /dev/null
-else
-	@$(ECHO) ".installPackageIndices('.', '"$(DPKG)"')" | \
-	  $(RHOME)/bin/rterm.exe --vanilla --slave R_DEFAULT_PACKAGES=tools LC_COLLATE=C > /dev/null
-endif
+	@$(ECHO) "tools:::.install_package_indices('.', '"$(DPKG)"')" | \
+	  R_DEFAULT_PACKAGES=NULL LC_COLLATE=C R_OSTYPE=windows $(REXE) > /dev/null
 # need not have HTML installed when building packages
 	@$(MKDIR) -p $(RHOME)/doc/html/search
 	@$(CAT) $(RHOME)/library/*/CONTENTS > $(RHOME)/doc/html/search/index.txt	
@@ -299,13 +287,44 @@ endif
 	  $(RHOME)/share/perl/build-help-windows.pl -htmllists
 
 md5sums:
-ifneq ($(strip $(PKG)),base)
 	@$(ECHO) "  adding MD5 sums"
+	@$(ECHO) "tools:::.installMD5sums('"$(DPKG)"')" | \
+	  R_DEFAULT_PACKAGES=NULL LC_COLLATE=C R_OSTYPE=windows $(REXE) > /dev/null
+
 ifeq ($(strip $(BUILD)),CROSS)
-	@$(ECHO) ".installMD5sums('"$(DPKG)"')" | \
-	  R_DEFAULT_PACKAGES=tools LC_COLLATE=C R_OSTYPE=windows $(R_EXE) --vanilla --slave > /dev/null
-else
-	@$(ECHO) ".installMD5sums('"$(DPKG)"')" | \
-	  $(RHOME)/bin/rterm.exe --vanilla --slave R_DEFAULT_PACKAGES=tools LC_COLLATE=C > /dev/null
+R_X_BUILD=yes
 endif
+
+lazyload:
+	@if test -d $(DPKG)/R ; then \
+	  if ! test -f $(DPKG)/R/$(PKG).rdb ; then \
+	    $(ECHO)  "  preparing package $(PKG) for lazy loading" ; \
+            (if test -s $(SPKG0)/R_PROFILE.R; then cat $(SPKG0)/R_PROFILE.R; fi; \
+	      $(ECHO) "invisible(.libPaths(c(.Library,\"$(RLIB)\", .libPaths()))); .getRequiredPackages(\"$(SPKG0)/DESCRIPTION\",useImports=TRUE); Sys.putenv('R_CROSS_BUILD'='$(R_X_BUILD)'); tools:::makeLazyLoading(\"$(PKG)\", lib.loc=\"$(RLIB)\")") | \
+	      R_DEFAULT_PACKAGES=$(R_START_PACKAGES) \
+	      LC_COLLATE=C R_OSTYPE=windows $(REXE) > /dev/null || exit 1; \
+	    rm -f $(DPKG)/R/all.rda ; \
+	    if test -r install.R ; then \
+	      cat install.R >> $(DPKG)/R/$(PKG) ; \
+	    fi ; \
+	  fi ; \
+	fi
+
+lazydata:
+	@if test -d $(DPKG)/data; then \
+	  if ! test -f $(DPKG)/data/Rdata.rdb ; then \
+	    $(ECHO)  "  preparing package $(PKG) for lazy data loading" ; \
+	    $(ECHO) "tools:::data2LazyLoadDB(\"$(PKG)\", lib.loc=\"$(RLIB)\")" | \
+	      R_CROSS_BUILD=$(R_X_BUILD) R_DEFAULT_PACKAGES=NULL \
+	      LC_COLLATE=C R_OSTYPE=windows $(REXE) > /dev/null  || exit 1; \
+	  fi ; \
+	fi
+
+SYSDATA=$(wildcard $(SPKG)/R/sysdata.rda)
+
+sysdata:
+ifneq ($(strip $(SYSDATA)),)
+	$(ECHO)  "    preparing to lazyload sysdata"
+	$(ECHO) "tools:::sysdata2LazyLoadDB(\"$(SYSDATA)\", \"$(DPKG)/R\")" | \
+	      R_DEFAULT_PACKAGES=NULL $(REXE) > /dev/null || exit 1
 endif
